### ISSUE TITLE
[Documentation] Duplicate content on content-modeling page

### ISSUE THREAD

**Issue by gmazza** [perfectsense/brightspot-cms#1007]
On the content modeling page:  http://documentation.brightspot.com/docs/3.2/content-modeling

The "field types" and "adding field types" chapters in the left-side table of contents appear to be identical, one of the two can be removed.

**Comment by rhino88** [comment]
Thanks gmazza, we've removed the duplicated content on the docs site here: 

http://docs.brightspot.com/cms/developers-guide/content-modeling/all.html#adding-field-types
