### ISSUE TITLE
How to display a page which do not have any landing page content type?

### ISSUE THREAD

**Issue by kartheek-a** [perfectsense/brightspot-cms#1027]
Hi All,

I'm new to BrightSpot and this question may look silly.

How can we render any listing page(list of Articles) or any static page which will not have any content type associated with it. As I can see that if we have to assign a URL to website only way we can do is by generating URL in content item.

Thanks in Advance.
Kartheek

**Comment by rhino88** [comment]
Hi katheek-a,

There are a couple of ways that we can accomplish this, but the recommended approach _is_ to create a new Content type for Landing Pages. This will allow you to leverage the CMS for things like URL creation and previewing Landing Pages before publishing.

# Option 1 - Landing Page Content Type (Recommended)

This first option uses a new Content Type for Landing Page.

## Content Model

### Landing Page:

```
@Renderer.LayoutPath("/WEB-INF/page/layout.jsp")
@Renderer.Path("/WEB-INF/page/landing.jsp")
public class LandingPage extends Content implements Directory.Item {

    @Required
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Article> getArticles() {
        // This Query will most likely need additional predicates
        return Query.from(Article.class).select(0, 10).getItems();
    }

    @Override
    public String createPermalink(Site site) {
        // Create your URL automatically
        return StringUtils.toNormalized(this.getName());
    }
}
```

### Article:

```

@Renderer.LayoutPath("/WEB-INF/page/layout.jsp")
@Renderer.Paths({
        @Renderer.Path(value = "/WEB-INF/page/article.jsp"),
        @Renderer.Path(value = "/WEB-INF/module/article-preview.jsp", context = "preview")
})
public class Article extends Content {

    private String title;

    private Image image;

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Image getImage() {
        return image;
    }

    public void setImage(Image image) {
        this.image = image;
    }
}

```

## JSPs (Renderers)

### layout.jsp (created @ WEB-INF/page/)

This JSP will be used for common layout components, such as the Header/Footer of your site. For now, I've left comments where you can implement your own Header/Footer rendering.

```

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"  %>
<%@ taglib prefix="cms" uri="http://psddev.com/cms"  %>

<%-- Render Header Here --%>

<cms:render value="${mainContent}"/>

<%-- Render Footer Here --%>

```

### landing.jsp (created @ WEB-INF/page/)

The landing.jsp will be rendered by the `cms:render` usage in the above `layout.jsp` implementation. Note that we are using the `preview` context for rendering each of our `Article`s. This will render each `Article` using the `Renderer.Path` with a context value of "preview".

```

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"  %>
<%@ taglib prefix="cms" uri="http://psddev.com/cms"  %>

<div class="landing-page">
    <c:forEach items="${content.getArticles()}" var="article">
        <cms:render value="article" context="preview"/>
    </c:forEach>
</div>

```

### article-preview.jsp (created @ WEB-INF/module/)

```

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"  %>
<%@ taglib prefix="cms" uri="http://psddev.com/cms"  %>

<div class="article-preview">
    <cms:img src="${content.image}"/>
    <c:out value="${content.title}"/>
</div>

```

Let me know if you have any further questions about this example


# Options 2 (Not Recommended)

I realize your question was specifically requesting to _avoid_ creating a new Content type, which may mean you have a unique use case. If that is the case, you could use an HttpServlet to implement your own rendering logic. The below example will demonstrate a similar rendered result as Option 1.

```

@WebServlet("/landing")
public class LandingPageServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        WebPageContext page = new WebPageContext(getServletContext(), request, response);

        page.writeStart("div", "class", "landing-page");
            for (Article article : getArticles()) {
                ContextTag.Static.pushContext(request, "preview");
                PageFilter.renderObject(request, response, page, article);
                ContextTag.Static.popContext(request);
            }
        page.writeEnd();
    }

    public List<Article> getArticles() {
        // This Query will most likely need additional predicates
        return Query.from(Article.class).select(0, 10).getItems();
    }
}
```

Hopefully this helps with your question.

**Comment by rhino88** [comment]
@kartheek-a I'm going to go ahead and close this issue for now, but let us know if you have additional questions.
