### ISSUE TITLE
Maven installation issues

### ISSUE THREAD

**Issue by wattdjaun** [perfectsense/brightspot-cms#1039]
Hi everyone,

I'm running into a problem installing brightspot with Maven. 

This seems to be the problem:

[INFO] SystemJS build failed!
[INFO] Fatal error: Error on fetch for undefined.js at file:///C:/Users/Administ
rator/bright/undefined.js
[INFO]  ENOENT: no such file or directory, open 'C:\Users\Administrator\bright\u
ndefined.js'

But, i don't know what step i've missed to produce this undefined.js file. The file is not in the directory, so i'm wondering how i'm kinda stuck unless i can figure out what step i've missed.

Do anyone have any clue to this?
It is very much appreciated.
Thanks
Dj

Here's the non-debug version:
C:\Users\Administrator\bright>mvn -P run clean package cargo:run
[INFO] Scanning for projects...
[INFO]
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethrea
ded.SingleThreadedBuilder with a thread count of 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building com.project: bright 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://artifactory.psdops.com/public/com/psddev/cms-db/3.2-SNAPSHO
T/maven-metadata.xml
Downloaded: https://artifactory.psdops.com/public/com/psddev/cms-db/3.2-SNAPSHOT
/maven-metadata.xml (745 B at 0.7 KB/sec)
Downloading: https://artifactory.psdops.com/public/com/psddev/cms/3.2-SNAPSHOT/m
aven-metadata.xml
Downloaded: https://artifactory.psdops.com/public/com/psddev/cms/3.2-SNAPSHOT/ma
ven-metadata.xml (997 B at 4.8 KB/sec)
Downloading: https://artifactory.psdops.com/public/com/psddev/cms-hunspell/3.2-S
NAPSHOT/maven-metadata.xml
Downloaded: https://artifactory.psdops.com/public/com/psddev/cms-hunspell/3.2-SN
APSHOT/maven-metadata.xml (751 B at 3.3 KB/sec)
Downloading: https://artifactory.psdops.com/public/com/psddev/cms-tool-ui/3.2-SN
APSHOT/maven-metadata.xml
Downloaded: https://artifactory.psdops.com/public/com/psddev/cms-tool-ui/3.2-SNA
PSHOT/maven-metadata.xml (750 B at 3.6 KB/sec)
[INFO]
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ bright ---
[INFO] Deleting C:\Users\Administrator\bright\target
[INFO] Deleting C:\Users\Administrator\bright\src\main\webapp\WEB-INF (includes
= [classes/**, lib/**], excludes = [])
[INFO]
[INFO] --- build-helper-maven-plugin:1.9.1:add-source (add-view-classes) @ brigh
t ---
[INFO] Source directory: C:\Users\Administrator\bright\target\generated-sources\
styleguide added.
[INFO]
[INFO] --- gmaven-plugin:1.0:execute (create-build-properties) @ bright ---
[INFO] Generating build.properties file.
[INFO] Property: javaGeneratedSourcesDirectory=C:\Users\Administrator\bright\tar
get\generated-sources
[INFO] Property: name=com.project: bright
[INFO] Property: resourceDirectory=C:\Users\Administrator\bright\src\main\resour
ces
[INFO] Property: sourceFilter.webappSources=C:\Users\Administrator\bright\src\ma
in\webapp
[INFO] Property: sourceFilter.javaSources=C:\Users\Administrator\bright\src\main
\java
[INFO] Property: buildDate=Thu Oct 06 17:31:03 CDT 2016
[INFO] Property: classFinder.include=true
[INFO] Property: webappSourceDirectory=C:\Users\Administrator\bright\src\main\we
bapp
[INFO] Property: sourceFilter.javaGeneratedSources=C:\Users\Administrator\bright
\target\generated-sources
[INFO] Property: version=1.0-SNAPSHOT
[INFO] Property: javaSourceDirectory=C:\Users\Administrator\bright\src\main\java

[INFO]
[INFO] --- frontend-maven-plugin:0.0.26:install-node-and-npm (install-node-and-n
pm) @ bright ---
[INFO] Found proxies: []
[INFO] Node v4.2.1 is already installed.
[INFO] Found NPM version 2.14.7
[INFO]
[INFO] --- frontend-maven-plugin:0.0.26:npm (npm) @ bright ---
[INFO] Found proxies: []
[INFO] Running 'npm install --color=false' in C:\Users\Administrator\bright
[ERROR] npm WARN deprecated es6-module-loader@0.17.8: This project has been depr
ecated for "npm install es-module-loader" based on the newer loader spec.
[INFO] brightspot-styleguide@1.1.0 node_modules\brightspot-styleguide
[INFO] â??â??â?? normalize.css@3.0.3
[INFO] â??â??â?? daemon@1.1.0
[INFO] â??â??â?? recursive-readdir-sync@1.0.6
[INFO] â??â??â?? marked@0.3.6
[INFO] â??â??â?? sticky-kit@1.1.3
[INFO] â??â??â?? minimist@1.2.0
[INFO] â??â??â?? geopattern@1.2.3 (extend@1.2.1)
[INFO] â??â??â?? md5@2.0.0 (charenc@0.0.1, crypt@0.0.1, is-buffer@1.0.2)
[INFO] â??â??â?? chance@0.8.0
[INFO] â??â??â?? traverse@0.6.6
[INFO] â??â??â?? font-awesome@4.6.3
[INFO] â??â??â?? body-parser@1.14.1 (bytes@2.1.0, content-type@1.0.2, depd@1.1.0
, qs@5.1.0, on-finished@2.3.0, http-errors@1.3.1, debug@2.2.0, iconv-lite@0.4.12
, type-is@1.6.13, raw-body@2.1.7)
[INFO] â??â??â?? express@4.14.0 (escape-html@1.0.3, array-flatten@1.1.1, utils-m
erge@1.0.0, cookie-signature@1.0.6, content-type@1.0.2, merge-descriptors@1.0.1,
 encodeurl@1.0.1, methods@1.1.2, range-parser@1.2.0, serve-static@1.11.1, etag@1
.7.0, path-to-regexp@0.1.7, parseurl@1.3.1, vary@1.1.0, fresh@0.3.0, content-dis
position@0.5.1, cookie@0.3.1, depd@1.1.0, qs@6.2.0, on-finished@2.3.0, finalhand
ler@0.5.0, debug@2.2.0, proxy-addr@1.1.2, type-is@1.6.13, accepts@1.3.3, send@0.
14.1)
[INFO] â??â??â?? iframe-resizer@3.5.0
[INFO] â??â??â?? less-middleware@2.2.0 (node.extend@1.1.6, mkdirp@0.5.1)
[INFO] â??â??â?? jquery@2.1.4
[INFO] â??â??â?? terminal-kit@0.15.12 (array-kit@0.0.1, string-kit@0.2.10, async
-kit@0.6.10, tree-kit@0.5.26)
[INFO] â??â??â?? codemirror@5.9.0
[INFO] â??â??â?? connect-fonts@2.0.2 (mime@1.2.11, filed@0.1.0, tmp@0.0.23, oppr
essor@0.0.1, node-font-face-generator@0.1.5)
[INFO] â??â??â?? handlebars@4.0.5 (async@1.5.2, source-map@0.4.4, optimist@0.6.1
, uglify-js@2.7.3)
[INFO] â??â??â?? moment@2.15.1
[INFO] â??â??â?? lodash@3.10.1
[INFO] â??â??â?? less@2.7.1 (graceful-fs@4.1.9, mime@1.3.4, image-size@0.5.0, so
urce-map@0.5.6, errno@0.1.4, mkdirp@0.5.1, promise@7.1.1)
[INFO] â??â??â?? xml2js@0.4.17 (sax@1.2.1, xmlbuilder@4.2.1)
[INFO] â??â??â?? connect-fonts-opensans@0.0.5
[INFO]
[INFO] bsp-grunt@4.0.0 node_modules\bsp-grunt
[INFO] â??â??â?? dotenv@2.0.0
[INFO] â??â??â?? extend@3.0.0
[INFO] â??â??â?? xml2js@0.4.15 (sax@1.2.1, xmlbuilder@8.2.2)
[INFO] â??â??â?? path@0.12.7 (process@0.11.9, util@0.10.3)
[INFO] â??â??â?? time-grunt@1.3.0 (number-is-nan@1.0.1, hooker@0.2.3, text-table
@0.2.0, date-time@1.1.0, figures@1.7.0, pretty-ms@2.1.0, chalk@1.1.3)
[INFO] â??â??â?? grunt-contrib-copy@1.0.0 (file-sync-cmp@0.1.1, chalk@1.1.3)
[INFO] â??â??â?? grunt-bower-install-simple@1.2.3 (chalk@1.1.3)
[INFO] â??â??â?? systemjs-plugin-babel@0.0.12
[INFO] â??â??â?? grunt-contrib-clean@1.0.0 (async@1.5.2, rimraf@2.5.4)
[INFO] â??â??â?? grunt-postcss@0.8.0 (diff@2.2.3, chalk@1.1.3, postcss@5.2.4)
[INFO] â??â??â?? es6-module-loader@0.17.8 (when@3.7.7)
[INFO] â??â??â?? grunt-jsonlint@1.0.6 (strip-json-comments@1.0.4, jsonlint@1.6.2
)
[INFO] â??â??â?? autoprefixer@6.1.0 (num2fraction@1.2.2, postcss-value-parser@3.
3.0, browserslist@1.0.1, postcss@5.2.4, caniuse-db@1.0.30000547)
[INFO] â??â??â?? grunt-contrib-watch@1.0.0 (async@1.5.2, tiny-lr@0.2.1, lodash@3
.10.1, gaze@1.1.2)
[INFO] â??â??â?? grunt-contrib-less@1.3.0 (async@1.5.2, chalk@1.1.3, less@2.6.1)

[INFO] â??â??â?? lodash@4.16.4
[INFO] â??â??â?? babel-polyfill@6.16.0 (regenerator-runtime@0.9.5, babel-runtime
@6.11.6, core-js@2.4.1)
[INFO] â??â??â?? systemjs-builder@0.15.23 (data-uri-to-buffer@0.0.4, source-map@
0.5.6, mkdirp@0.5.1, glob@7.1.0, bluebird@3.4.6, rollup@0.31.2, systemjs@0.19.39
, uglify-js@2.7.3, traceur@0.0.105, es6-template-strings@2.0.1, babel-core@6.17.
0, babel-plugin-transform-es2015-modules-systemjs@6.14.0)
[INFO] â??â??â?? bower@1.7.9
[INFO]
[INFO] --- frontend-maven-plugin:0.0.26:grunt (grunt) @ bright ---
[INFO] Running 'grunt --bsp-maven-build-finalName=bright-1.0-SNAPSHOT --no-color
' in C:\Users\Administrator\bright
[INFO] Running "bsp-config-dest" task
[INFO] target/bright-1.0-SNAPSHOT
[INFO]
[INFO] Running "clean:destCSS" (clean) task
[INFO] >> 0 paths cleaned.
[INFO]
[INFO] Running "clean:sourceCSS" (clean) task
[INFO] >> 0 paths cleaned.
[INFO]
[INFO] Running "bower-prune" task
[INFO] Pruned extraneous Bower packages.
[INFO]
[INFO] Running "bower-install-simple:all" (bower-install-simple) task
[INFO] Executing Bower (Command: install)
[INFO]
[INFO] Running "bower-configure-copy" task
[INFO] Configured brightspot-base: "base/**", "community/**"
[INFO] Configured bsp-utils: bsp-utils.js
[INFO] Configured jquery: jquery.js
[INFO] Configured normalize-css: ["bower_components\\normalize-css/normalize.css
"]
[INFO]
[INFO] Running "copy:bower" (copy) task
[INFO] Created 9 directories, copied 71 files
[INFO]
[INFO] Running "create-binaries" task
[INFO] Created binary: node
[INFO] Created binary: bower
[INFO] Created binary: styleguide
[INFO] Created binary: grunt
[INFO] Created binary: grunt
[INFO]
[INFO] Running "copy:styles" (copy) task
[INFO] Created 12 directories, copied 65 files
[INFO]
[INFO] Running "less:compile" (less) task
[INFO]
[INFO] Running "bsp-autoprefixer" task
[INFO] Running autoprefixer
[INFO]
[INFO] Running "postcss:autoprefixer" (postcss) task
[INFO] >> No source files were found.
[INFO]
[INFO] Running "copy:scripts" (copy) task
[INFO] Created 1 directory, copied 1 file
[INFO]
[INFO] Running "systemjs:dist" (systemjs) task
[INFO] >> SystemJs configured with:
[INFO] { minify: true, polyfills: true, sourceMaps: true }
[INFO] SystemJS build failed!
[INFO] Fatal error: Error on fetch for undefined.js at file:///C:/Users/Administ
rator/bright/undefined.js
[INFO]  ENOENT: no such file or directory, open 'C:\Users\Administrator\bright\u
ndefined.js'
[INFO]
[INFO]
[INFO] Execution Time (2016-10-06 22:32:03 UTC)
[INFO] loading tasks              1.4s  â??â??â??â??â??â??â??â??â??â??â??â??â??â
??â??â??â??â??â??â??â?? 57%
[INFO] bsp-config-dest            47ms  â?? 2%
[INFO] clean:sourceCSS            31ms  â?? 1%
[INFO] bower-prune               516ms  â??â??â??â??â??â??â??â?? 21%
[INFO] bower-install-simple:all   47ms  â?? 2%
[INFO] bower-configure-copy       47ms  â?? 2%
[INFO] copy:bower                156ms  â??â??â?? 6%
[INFO] copy:styles               125ms  â??â?? 5%
[INFO] systemjs:dist              63ms  â?? 3%
[INFO] Total 2.5s
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:07 min
[INFO] Finished at: 2016-10-06T17:32:05-06:00
[INFO] Final Memory: 24M/225M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.26:
grunt (grunt) on project bright: Failed to run task: 'grunt --bsp-maven-build-fi
nalName=bright-1.0-SNAPSHOT --no-color' failed. (error code 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption

**Comment by rhino88** [comment]
Hi wattdjaun,

Can you try to create a `main.js` file inside your `src/main/webapp` directory? That should fix the issue.

Let us know if that works!

**Comment by wattdjaun** [comment]
Thanks, @rhino88! 
That did the trick! I appreciate your time!
Would have never guess that from the error messages.
Thanks
Dj

**Comment by rhino88** [comment]
Thanks for the feedback. We'll update our maven archetype to prevent this from happening in the future.

**Comment by sachinkaushik** [comment]
Hi rhino88,

I'm also getting same error while building this project. As per your suggestion I created a main.js file inside your src/main/webapp directory but it's not working. Please suggest.

Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.26:grunt (grunt) on project cms-tool-ui: Failed to run task: 'grunt --bsp-maven-build-finalName=cms-tool-ui-3.2-SNAPSHOT --no-color' failed. (error code 3) -> [Help 1]

I

**Comment by sachinkaushik** [comment]
Hi @wattdjaun n @rhino88,

I'm facing same issue. Can you please help me.?

**Comment by ramanshankrit** [comment]
Hi @wattdjaun n @rhino88, @sachinkaushik 
even i am facing the same issue and tried to solve by creating main.js but it still giving the same error. please help.


[ERROR] npm WARN deprecated es6-module-loader@0.17.8: This project has been depr
ecated for "npm install es-module-loader" based on the newer loader spec.
[ERROR] npm ERR! registry error parsing json
[ERROR] npm ERR! fetch failed https://registry.npmjs.org/ejs/-/ejs-1.0.0.tgz
[ERROR] npm WARN retry will retry, error on last attempt: Error: fetch failed wi
th status code 503
[ERROR] npm ERR! fetch failed https://registry.npmjs.org/ejs/-/ejs-1.0.0.tgz
[ERROR] npm WARN retry will retry, error on last attempt: Error: connect ETIMEDO
UT 151.101.8.162:443
[ERROR] npm ERR! fetch failed https://registry.npmjs.org/ejs/-/ejs-1.0.0.tgz
[ERROR] npm ERR! Windows_NT 6.1.7601
[ERROR] npm ERR! argv "D:\\mysoft\\brightspot-project\\BrightSpot\\node\\node.ex
e" "D:\\mysoft\\brightspot-project\\BrightSpot\\node\\node_modules\\npm\\bin\\np
m-cli.js" "install" "--color=false"
[ERROR] npm ERR! node v4.2.1
[ERROR] npm ERR! npm  v2.14.7
[ERROR]
[ERROR] npm ERR! fetch failed with status code 503
[ERROR] npm ERR!
[ERROR] npm ERR! If you need help, you may report this error at:
[ERROR] npm ERR!     <https://github.com/npm/npm/issues>
[ERROR]
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     D:\mysoft\brightspot-project\BrightSpot\npm-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:57 min
[INFO] Finished at: 2016-11-07T15:35:33+05:30
[INFO] Final Memory: 22M/246M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.26:
npm (npm) on project BrightSpot: Failed to run task: 'npm install --color=false'
 failed. (error code 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
