### ISSUE TITLE
Bug with querying for initial drafts in a workflow state

### ISSUE THREAD

**Issue by yuriydr** [perfectsense/brightspot-cms#1078]
We are occasionally running into an issue where we place an initial draft of a content item into a workflow state, and when we try to run a query that searches for objects of that type in that workflow state, the item cannot be found. There is only one way to reproduce the issue, and even then, it's not 100% reproducible, but fixing it is as simple as getting to that workflow state in any other way, or even just going to the Query section of the debug pages, finding the item by ID, "Edit Raw", and saving. Then regular queries are able to find that item.

The way to reproduce this issue, when it's reproducible, is by first saving an initial draft, and then performing a workflow transition into the desired state. The query that fails to find the item until one of the ways of fixing it is done is:

Query.from(Type.class).where("cms.workflow.currentState = 'XXX'")

Again, the only way we know to reproduce the issue is by a "Save Draft" (initial drafts only) followed by a workflow transition. Even skipping the "Save Draft" step and just performing the workflow transition immediately does not cause the issue to occur. Doing a circle around back to the workflow state through another workflow state (our workflow has those transitions) fixes the issue as well.

We tried this with multiple types of content, and they all behave the same.

Our Brightspot version is 3.2 Update 4 and our SOLR version is 4.8.1.

**Comment by rhino88** [comment]
Hi yuriydr,

This is working as expected. If you take a look at [Content's `draft` field](https://github.com/perfectsense/brightspot-cms/blob/release/3.2/db/src/main/java/com/psddev/cms/db/Content.java#L91) you will see the `@Indexed(visibility = true)` annotation. This is using the "visibility index" feature provided by Dari. What this means, is that any `Content` object with `draft = true` will not be returned in `Query` results, unless explicitly requested.

To request items in your given Workflow state regardless of draft status, I've modified your Query below:

```
Query.from(Type.class).where("cms.content.draft = missing || cms.content.draft = true").and(cms.workflow.currentState = 'XXX'")
```

**Comment by rhino88** [comment]
Closing this for now, as this is working as expected. Let us know if you have additional questions.

Thanks.

**Comment by yuriydr** [comment]
Thank you for your response.

When the content item is moved to its workflow state, the "cms.content.draft" field is removed from its state, and the "cms.workflow.currentState" field is added to it. The "dari.visibilities" field is also updated accordingly ("cms.content.draft" is removed from it, and "cms.workflow.currentState" is added to it). We can see this when viewing the object in _debug/query. Doesn't this mean that we should be able to query by using only the currentState field?
