### ISSUE TITLE
How to Setup BrightSpot on Eclipse. There is some maven plugin errors.

### ISSUE THREAD

**Issue by sachinkaushik** [perfectsense/brightspot-cms#1104]
Hi @rhino88 ,

I have setup project locally on my machine through the installation guide. But I want to setup BrightSpot on Eclipse(Oxygen) when I'm importing this project as a maven there is some plugin errors as given. 

**1. Plugin execution not covered by lifecycle configuration: org.codehaus.gmaven:groovy-maven-plugin:2.0:execute (execution: create-reflections-xml, phase: process-classes)
2. Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:exec-maven-plugin:1.2.1:java (execution: generate-view-classes, phase: process-resources)
3. Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:exec-maven-plugin:1.2.1:java (execution: enhance-classes, phase: compile)**

Can you please help me to Setup BrightSpot on Eclipse.?

Thank you in Advance.

**Comment by sachinkaushik** [comment]
Hi @rhino88 ,

 BrightSpot is successfully build on Eclipse but when I'm running it on tomcat server using **localhost:8080/eCMS/cms** login screen comes with no CSS because context look for CSS under **localhost:8080/cms** . On eclipse server its deploying on **"BrightWS\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\eCMS\cms"**  location.

Can you please help me what kind of configuration required for this.

**Comment by hyoolim** [comment]
This was fixed in #1097. Can you try running the project again?

**Comment by sachinkaushik** [comment]
Hi @rhino88 ,

I've setup BrightSpot on eclipse when I'm running this on server Dashboard is showing with getting below error.

Can't render /cms/dashboardWidget/default/com.psddev.cms.tool.widget.RecentActivityWidget/bbf6360b-12a6-3c9d-8ccd-60bc3e5d9894!

Expected mime type application/octet-stream but got text/html. <html><head><title>Apache Tomcat/7.0.72 - Error report</title><style></style> </head><body><h1>HTTP Status 404 - /solr/select</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>/solr/select</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.72</h3></body></html> (org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException)
org.apache.solr.client.solrj.impl.HttpSolrServer.executeMethod(HttpSolrServer.java:516)
org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:210)
org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:206)
Toggle Stack Traces
Parameters:
_=1480929538737 

Can you please help me on this.
Thank you in Advance.

**Comment by rhino88** [comment]
Hi sachinkaushik,

It looks like Solr is not configured correctly. For a quick and easy way to get up and running, you should take a look at our [Brightspot Tutorial](https://github.com/perfectsense/brightspot-tutorial) project, which is also [documented here](http://docs.brightspot.com/cms/getting-started/install/all.html#quick-installation).

If you would like to configure the environment yourself, you will need to follow the more advanced instructions here: http://docs.brightspot.com/cms/getting-started/install/all.html#development-installation

If you are still having issues, feel free to ask questions.

**Comment by rhino88** [comment]
Closing for now. Feel free to reopen if you still have questions
