### ISSUE TITLE
many-to-many with extra fields

### ISSUE THREAD

**Issue by ajayaks** [perfectsense/brightspot-cms#1107]
How to handle many to many relationship with extra fields in join table/entity?

Eg :- Entity A (3 fields) , Entity B(5 fields) , Entity AB(primary key of A, primary key of B + other 4 more fields which are not in Entity A)

Please suggest.

**Comment by hyoolim** [comment]
```java
class EntityAB {

    @Indexed
    EntityA a;

    @Indexed
    EntityB b;

    String extra1;
    String extra2;
    String extra3;
    String extra4;

    // If you want to enforce that A and B can only be related once.
    @Indexed(unique = true)
    @ToolUi.Hidden
    public String getAB() {
        return a.getId().toString() + ":" + b.getId().toString();
    }
}

// Get some B instances and the relation data
for (EntityAB ab : Query.from(EntityAB.class).where("a = ?").select(0, 5).getItems()) {
    EntityB b = ab.getB();
    String extra1 = ab.getExtra1();
}
```

**Comment by ajayaks** [comment]
Thanks for the response but i have another question attached to it.
Don't we have to refer this Entity AB class in Entity A or B?  Because in Entity A i was expecting List<Entity B> and other way also and on UI(for Entity A) i'll have List type where i can add objects of Entity B?

Please suggest.
