### ISSUE TITLE
Publishing with Required fields that have initial drafts set

### ISSUE THREAD

**Issue by lajoiechristina** [perfectsense/brightspot-cms#1108]
I wanted to ask if a particular behavior is working "as designed" or not.

I have a model which contains a field that is required (marked "@Required").  Lets call the model, "Container", and the field type, "Foo".  I have created a new _Foo_ and did **not** publish it; I only saved it, making it an initial draft.  I then created a _Container_, set _Foo_ on its field, and published it.  Even though _Foo_ is an initial draft and is not backed by any published object, _Container_ publishes successfully, without a validation error despite the "Required" annotation.  It appears that as long as _something_ is filled in that field, regardless of its visibility, it fulfills the requirement for the "Required" annotation.  I almost would have expected it to take into consideration the visibility of the object that is set on the required field.

Thanks!

**Comment by hyoolim** [comment]
This is the intended behavior.

Given your example, consider a `Container` instance that has the field filled out with a published and visible instance of `Foo`. If someone then archives that `Foo` instance, the `Container` instance is no longer "valid". Or if a developer adds the `@Required` annotation retroactively when there are existing instances of `Container` without the field filled out, all those instances are in "inconsistent" states.

Traditional databases solve this issue by either forbidding those types of changes or forcing a migration path that fixes all existing data to conform to the new constraints. Dari is designed to handle this at runtime (e.g. always check for `null`).

Also note that invisible items aren't always resolved to `null`. During a page preview, for example, the invisible items return as if they were visible to empower previewing of scheduled content.

**Comment by lajoiechristina** [comment]
Thank you for the quick response and clear explanation :+1:
