### ISSUE TITLE
Editing in popup view creates multiple drafts

### ISSUE THREAD

**Issue by lajoiechristina** [perfectsense/brightspot-cms#1109]
Performing the following steps causes multiple drafts to be created:

1. In Edit view for published content A, select "Edit" on a field whose value is an instance of a type that derives from Content (content B)
2. In the popup view for content B, select "Edit" on a field whose value is an instance of a type that derives from Content (content C)
3. In the popup view for content C, select "Save Draft"
4. Select "Edit in Full"
5. In the full view for content C, change something (text field perhaps)
6. Select "Save"
7. Select a workflow transition button
8. Observe that multiple drafts are on the published content C object

**Comment by rhino88** [comment]
Thanks for reporting this issue, it has now been fixed in the latest 3.2-SNAPSHOT
