### ISSUE TITLE
https://github.com/perfectsense/brightspot-cms/issues/1107

### ISSUE THREAD

**Issue by ajayaks** [perfectsense/brightspot-cms#1112]
Align with #1107.

Thanks for the response but i have another question attached to it.
Don't we have to refer this Entity AB class in Entity A or B? Because in Entity A i was expecting List and other way also and on UI(for Entity A) i'll have List type where i can add objects of Entity B?

Please suggest.

**Comment by ajayaks** [comment]
Any update on this? Please suggest

**Comment by rhino88** [comment]
Please take a look at the documentation here: http://docs.brightspot.com/cms/developers-guide/content-modeling/all.html#junction-field

In your scenario, you can add a `@JunctionField` to `EntityA`.

**Comment by ajayaks** [comment]
Do you mean i have to implement EntityAB ? As EntityAB is having some extra properties that are not in EntityA and Entity B.
Then add @Recordable.JunctionField("playlist")
    private List<EntityAB> abs;

Please suggest.

**Comment by rhino88** [comment]
Given the example provided, your usage could look like this:

```
class EntityAB {

    @Indexed
    EntityA a;

    @Indexed
    EntityB b;

    String extra1;
    String extra2;
    String extra3;
    String extra4;

    // If you want to enforce that A and B can only be related once.
    @Indexed(unique = true)
    @ToolUi.Hidden
    public String getAB() {
        return a.getId().toString() + ":" + b.getId().toString();
    }
}
```

```
class EntityA {
    String field1;
    String field2;

    @JunctionField("a")
    EntityAB relationship;
}
```

**Comment by rhino88** [comment]
Closing this issue for now. Feel free to reopen if you still have questions.
