### ISSUE TITLE
Event Handling in brightspot

### ISSUE THREAD

**Issue by alokstar** [perfectsense/brightspot-cms#1113]
Can we do event handling in Brightspot? If yes, do we have any documentation for the same which I can refer? My requirement for this, is as follows:
I have a content type (say Person) which has some properties. When I give the value to a certain property. I want additional properties to be shown on the UI according to the value given. The number of properties shown on the UI will vary depending on the value I have selected/given.

Thanks!

**Comment by rhino88** [comment]
Hi Alokstar,

Brightspot has the ability to support `@Embedded Record` fields that may provide an appropriate interface for your use case. Here is an example of what this could look like for a field of `Role` on a `Person` object, where different roles have different fields.

![image](https://cloud.githubusercontent.com/assets/1299507/21144765/d44d361c-c119-11e6-869d-a5f8c67916e0.png)


Here is what the data model looks like:

```
public class Person extends Content {

    private String firstName;
    private String lastName;
    private Role role;

    @Recordable.Embedded
    public abstract static class Role extends Record {
        String sharedField;
    }

    public static class Manager extends Role {
        String managerSpecificField;
    }

    public static class Developer extends Role {

        String developerSpecificField;
        String developerSpecificField2;
    }

    public static class Designer extends Role {
        String designerSpecificField;
    }
}
```

With this data model, Brightspot provides a dropdown for you to select one of the concrete types of `Role`, with each option having the ability to display fields specific to a given role.

Hopefully this solves your use case, let us know if you have any additional questions!

**Comment by mihirlibran** [comment]
Hi Rhino88,

Thank you for your response! It gave us a very good starting point. I will work on this and will surely update this thread should I get stuck.

**Comment by alokstar** [comment]
Hi Rhino88,
Thank you for the response. For now, it looks like a solution.
Thank you.

**Comment by rhino88** [comment]
Great! I'll go ahead and close this issue for now, but feel free to reopen.
