### ISSUE TITLE
Some annoying exceptions during build process

### ISSUE THREAD

**Issue by Typografikon** [perfectsense/brightspot-cms#1125]
Hi to all, 

there are some exceptions during build process ic current 3.2.6800-ed293d version. I believe that these problems can stop novices to try brightspot. Is there some change to fix it? It will be nice fix at least grunt fail and annoying `could not create Vfs.Dir from url` exception. 

So how to reproduce it: First create new project from archetype:

> mvn archetype:generate -B -DarchetypeRepository=https://artifactory.psdops.com/psddev -DarchetypeGroupId=com.psddev -DarchetypeArtifactId=cms-app-archetype -DarchetypeVersion=3.2.6800-ed293d -DgroupId=cz.typografikon -DartifactId=test-project -DmodelVersion=1.0-SNAPSHOT

 When you try to build project you got npm depreciation warning:

> cd test-project/
> mvn package
> (...)
> [INFO] Running 'npm install --color=false' in /home/ondrej/Workspacejava/test-projects/test-project
[ERROR] npm WARN deprecated es6-module-loader@0.17.8: This project has been deprecated for "npm install es-module-loader" based on the newer loader spec.

But build can continue. Unfortunately it fails later on grunt call:

> (...)
> [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.26:grunt (grunt) on project test-project: Failed to run task: 'grunt --bsp-maven-build-finalName=test-project-1.0-SNAPSHOT --no-color' failed. (error code 1) -> [Help 1]

You can try call grunt directly to see what problem occurs:

> grunt --bsp-maven-build-finalName=test-project-1.0-SNAPSHOT --no-color
> (...)
> SystemJs configured with:
{ minify: true, polyfills: true, sourceMaps: true }
SystemJS build failed!
Fatal error: Error on fetch for undefined.js at file:///home/ondrej/Workspacejava/test-projects/test-project/undefined.js
ENOENT: no such file or directory, open '/home/ondrej/Workspacejava/test-projects/test-project/undefined.js'

This problem can be overcomed this with:

> touch /home/ondrej/Workspacejava/test-projects/test-project/undefined.js
> grunt --bsp-maven-build-finalName=test-project-1.0-SNAPSHOT --no-color
> (...)
> Done.

Now maven build continue but there is one more annoying exception:

> [WARNING] could not create Vfs.Dir from url. ignoring the exception and continuing
com.psddev.dari.util.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/home/ondrej/.m2/repository/com/psddev/cms-tool-ui/3.2.6800-ed293d/cms-tool-ui-3.2.6800-ed293d.war]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
	at com.psddev.dari.util.reflections.vfs.Vfs.fromURL(Vfs.java:109)
	at com.psddev.dari.util.reflections.vfs.Vfs.fromURL(Vfs.java:91)
	at com.psddev.dari.util.reflections.Reflections.scan(Reflections.java:237)
	at com.psddev.dari.util.reflections.Reflections.scan(Reflections.java:204)
	at com.psddev.dari.util.reflections.Reflections.<init>(Reflections.java:129)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
	at script1.run(script1.groovy:10)

It looks this happens during process-classes when reflection is called from groovy script, but I didnt try to deal with it because build can continue and finnaly succeed:

> [INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

Tested on Linux MInt 18 Cinnamon 64 bit, Openjdk version "1.8.0_111", Apache Maven 3.3.9, grunt-cli v1.2.0, npm 3.5.2.

With best regards, 
O.

**Comment by rhino88** [comment]
Thanks for the feedback.

**NPM Errors:**

We've updated our front end build process to use [Gulp](http://gulpjs.com/) and [Yarn](https://yarnpkg.com/). You can take a look at the new configuration in our [Brightspot Tutorial Project](https://github.com/perfectsense/brightspot-tutorial). The new [Quick Installation] (http://docs.brightspot.com/cms/getting-started/install/all.html#quick-installation) docs also reference this repository.

**Maven Stacktraces**

They are currently identified as `[WARNING]`s in the build output,  and can be safely ignored. We would like to remove these from the build output, but it's relatively low priority. It is currently logged as a minor issue.

**Comment by Typografikon** [comment]
Thanks for response. Is it so that later will be new front end build process used also in brightspot-cms?
