### ISSUE TITLE
Many opened sessions while working in brightspot cms admin UI

### ISSUE THREAD

**Issue by Typografikon** [perfectsense/brightspot-cms#1126]
Hi, 

I noticed that there is about 200 or more http session opened while working in brightspot cms admin UI. Not sure why is it so. These sessions looks like empty - at least when inspecting with Tomcat Manager.

When accessing normal website sessions works as usually (which means ~1 session for one browser).

Is it expected behaviour? I am afraid that server will be overloaded when more clients will be accessing admin UI.

Best regards,
O.

**Comment by rhino88** [comment]
Hey Ondřej,

What you are seeing is nothing to worry about. You are likely seeing sessions created by Tomcat (Brightspot does not create them). There is no way to completely disable them, as they are a part of the Java Servlet spec. 

The next best thing you can do is to configure your Tomcat to [limit sessions persistence](http://tomcat.apache.org/tomcat-7.0-doc/config/manager.html#Disable_Session_Persistence).

However, it is worth mentioning that we do not do this ourselves in production, even with hundreds of concurrent CMS users.

**Comment by Typografikon** [comment]
What part of Java Servlet spec do you mean? I never noticed so many sessions in single user admin ui. I created some admins ui with help of Ext JS - JavaScript framework (which extensively uses ajax, tiny iframes etc...) and tomcat as application server. These administrations took exactly 1 http sesion for 1 logged user. However, I used no server side events or web sockets.

**Comment by rhino88** [comment]
Brightspot does not create any sessions and also forbids the usage of sessions via the [NoSessionFilter](https://github.com/perfectsense/dari/blob/release/3.2/util/src/main/java/com/psddev/dari/util/NoSessionFilter.java).

If you can show us a screenshot or log that demonstrates what you are seeing, perhaps we can provide additional information.

**Comment by Typografikon** [comment]
Many thanks, it looks like problem is that one of my own filters *creates session* but NoSessionFilter *invalidates these session*. This happens in each request. As a result there are plenty plenty invalidated sessions. I can verify my thesis if there is some way how to disable NoSessionFilter.
