### ISSUE TITLE
Expected mime type application/octet-stream but got text/html. 

### ISSUE THREAD

**Issue by ajayaks** [perfectsense/brightspot-cms#1133]
Hi , 
I am getting below issue after login.

Can't render /cms/misc/searchResult.jsp!

Expected mime type application/octet-stream but got text/html. <html><head><title>Apache Tomcat/7.0.73 - Error report</title><style></style> </head><body><h1>HTTP Status 404 - /solr/select</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>/solr/select</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.73</h3></body></html> (org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException)

I have placed slf4j jars in tomcat/lib folder.

Please suggest.

**Comment by rhino88** [comment]
Hi ajayaks, this indicates that Solr is not configured correctly in Tomcat. Please double check your Tomcat + Solr configuration using the steps [here](http://docs.brightspot.com/cms/getting-started/install/all.html#development-installation). Alternatively, you can follow our [Quick Installation Guide](http://docs.brightspot.com/cms/getting-started/install/all.html#quick-installation) and you won't have to worry about setting everything up yourself.

**Comment by ajayaks** [comment]
Yup, it was due to wrong solr file name. Thanks for your support.
