### ISSUE TITLE
Sources and javadocs for com.psddev.* cannot be downloaded via Maven

### ISSUE THREAD

**Issue by Typografikon** [perfectsense/brightspot-cms#1137]
Hi to all, 

I cannot download source and javadoc jars via Maven. When I create project from cms-app-archetype, for example:

> mvn archetype:generate \
-B -DarchetypeRepository=https://artifactory.psdops.com/psddev \
-DarchetypeGroupId=com.psddev \
-DarchetypeArtifactId=cms-app-archetype \
-DarchetypeVersion=3.2.6800-ed293d \
-DgroupId=cz.typografikon \
-DartifactId=test-project \
-DmodelVersion=1.0-SNAPSHOT;

source and javadocs cannot be resolved:

> mvn dependency:sources
(...)
[INFO] The following files have NOT been resolved:
[INFO]    com.psddev:dari-asm:jar:sources:3.2.2296-7fc809:compile
[INFO]    com.psddev:cms-tool-ui:war:sources:3.2.6800-ed293d:compile
[INFO]    com.psddev:dari-sms:jar:sources:3.2.2296-7fc809:compile
[INFO]    com.psddev:dari-mail:jar:sources:3.2.2296-7fc809:compile
[INFO]    com.psddev:cms-db:jar:sources:3.2.6800-ed293d:compile
[INFO]    com.psddev:dari-storage:jar:sources:3.2.2296-7fc809:compile
[INFO]    com.psddev:cms-hunspell:jar:sources:3.2.6800-ed293d:compile
[INFO]    com.psddev:dari-image:jar:sources:3.2.2296-7fc809:compile
[INFO]    com.psddev:handlebars:jar:sources:1.2.101-12aba4:compile
[INFO]    com.psddev:dari-db:jar:sources:3.2.2296-7fc809:compile
[INFO]    com.psddev:dari-aws:jar:sources:3.2.2296-7fc809:compile
[INFO]    com.amazonaws:aws-java-sdk:jar:sources:1.10.15:compile
[INFO]    com.psddev:dari-reflections:jar:sources:3.2.2296-7fc809:compile
[INFO]    com.psddev:dari-util:jar:sources:3.2.2296-7fc809:compile
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

and 

> mvn dependency:resolve -Dclassifier=javadoc
(...)
[INFO] The following files have NOT been resolved:
[INFO]    com.psddev:dari-sms:jar:javadoc:3.2.2296-7fc809:compile
[INFO]    com.psddev:cms-hunspell:jar:javadoc:3.2.6800-ed293d:compile
[INFO]    com.psddev:dari-aws:jar:javadoc:3.2.2296-7fc809:compile
[INFO]    taglibs:standard:jar:javadoc:1.1.2:compile
[INFO]    com.psddev:cms-tool-ui:war:javadoc:3.2.6800-ed293d:compile
[INFO]    com.psddev:dari-mail:jar:javadoc:3.2.2296-7fc809:compile
[INFO]    com.psddev:dari-db:jar:javadoc:3.2.2296-7fc809:compile
[INFO]    com.psddev:dari-util:jar:javadoc:3.2.2296-7fc809:compile
[INFO]    javax.activation:activation:jar:javadoc:1.1:compile
[INFO]    mysql:mysql-connector-java:jar:javadoc:5.1.35:compile
[INFO]    com.psddev:dari-image:jar:javadoc:3.2.2296-7fc809:compile
[INFO]    org.codehaus.woodstox:wstx-asl:jar:javadoc:3.2.7:compile
[INFO]    com.psddev:dari-storage:jar:javadoc:3.2.2296-7fc809:compile
[INFO]    com.psddev:dari-reflections:jar:javadoc:3.2.2296-7fc809:compile
[INFO]    javax.servlet:jstl:jar:javadoc:1.1.2:compile
[INFO]    com.psddev:cms-db:jar:javadoc:3.2.6800-ed293d:compile
[INFO]    com.amazonaws:aws-java-sdk:jar:javadoc:1.10.15:compile
[INFO]    org.codehaus.jackson:jackson-core-asl:jar:javadoc:1.6.1:compile
[INFO]    com.psddev:dari-asm:jar:javadoc:3.2.2296-7fc809:compile
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

Because I see sources and javadocs here in repository  

- https://artifactory.psdops.com/public/com/psddev/cms/3.2.6800-ed293d/
- https://artifactory.psdops.com/public/com/psddev/dari/3.2.2296-7fc809/

I download them by hand and attach successfully in Intellij IDEA. But it will be nice to perform this automagically. Just a wish :-)

Best regards,
O.

**Comment by detec** [comment]
This feature is really needed.
