### ISSUE TITLE
Update and save object itself in afterSave() method

### ISSUE THREAD

**Issue by Typografikon** [perfectsense/brightspot-cms#1138]
Hi all. 

I need more explanation about defferences between these methods:

- Record.save();
- Record.saveImmediately();
- Record.saveEventually();
- Record.saveUniquely();

I try to trigger action after record is saved. These action should update several objects including record itself. Currently I use:

```java
class Sample extends Record {
	// ...some other fields...
	@Override
	protected void afterSave() {
		// ...some other operations...
		setSomeField(...);
		saveImmediately();
	}
}
```
I need afterSave because I want to trigger action only when Publish button is clicked (but not when some field is changed and validated). In afterSave I need to save record itself, otherwise it will not be persisted. It looks like saveImmediately works fine. But I am not sure it is best way to do it?

Example in documentation http://documentation.brightspot.com/docs/3.2/content-modeling/data-validation#after-save is not clear - it looks there is missing saveImmediately() call. Can You also check it?

Best regards,
O.

**Comment by rhino88** [comment]
For your use case we would recommend using [beforeCommit()](https://github.com/perfectsense/dari/blob/release/3.2/db/src/main/java/com/psddev/dari/db/Record.java#L92) which only happens once before the item is committed to the database. It's a relatively new method, and we have not yet had a chance to add it to the documentation.

As for the other methods you mention, here is a quick summary:

* [State#saveImmediately()](https://github.com/perfectsense/dari/blob/release/3.2/db/src/main/java/com/psddev/dari/db/State.java#L2214)

Begins an isolated write transaction with the database. Useful when you are batching writes to the database but need to save something "immediately" outside of the current transaction.

* [State#saveEventually()](https://github.com/perfectsense/dari/blob/release/3.2/db/src/main/java/com/psddev/dari/db/State.java#L2229)

This was useful with Solr 3.x, but is not really necessary with Solr 4+. Should be deprecated.

* [State#saveUniquely()](https://github.com/perfectsense/dari/blob/release/3.2/db/src/main/java/com/psddev/dari/db/State.java#L2249)

Not commonly used, we may also consider deprecating this one.

**Comment by Typografikon** [comment]
Many thanks for clarification! I believe it should be also included in documentation.
