### ISSUE TITLE
RepeatingTask synchronization 

### ISSUE THREAD

**Issue by Typografikon** [perfectsense/brightspot-cms#1139]
One more simple question: Guarantee RepeatingTask that **only one task will operate in the same time**?
Lets say that we have task which should import some data every 5 minutes. What happens in case that single import takes 10 minutes? Should I include simple synchronization semaphor in my RepeatingTasks?

With best regards,
O.

**Comment by rhino88** [comment]
Dari handles this for you. Only one instance of a RepeatingTask will run at any given time, per host.

**Comment by Typografikon** [comment]
Great, thanks for response!
