### ISSUE TITLE
How to setup default MailProvider in Brightspot

### ISSUE THREAD

**Issue by zalakdedhia** [perfectsense/brightspot-cms#1148]
Trying to use the MailMessage contenttype to send emails from my Brightspot CMS app, how do I provide the default MailProvider

Getting this error
[2016-12-29 20:21:27,148][WARN ][db.AbstractDatabase$AfterSaveTrigger] Couldn't run afterSave on [00000159-4c31-d993-a77f-4c3fc6fb0000] java.lang.IllegalStateException: No default mail provider setting found!

**Comment by rhino88** [comment]
Hi zalakdedhia, 

To enable your MailProvider you will need to add configuration to your `context.xml`. Here is an example configuration, using the dari provided `SmtpMailProvider`.

```

    <Environment name="dari/defaultMailProvider" value="smtp" type="java.lang.String" />
    <Environment name="dari/mailProvider/smtp/class" value="com.psddev.dari.util.SmtpMailProvider" type="java.lang.String" />
    <Environment name="dari/mailProvider/smtp/host" value="YOUR_SMTP_HOST_HERE" type="java.lang.String" />
    <Environment name="dari/mailProvider/smtp/username" value="YOUR_USERNAME_HERE" type="java.lang.String" />

```

I've also made a note to add this to our documentation. Thanks!
