### ISSUE TITLE
How to provide a combination unique key

### ISSUE THREAD

**Issue by zalakdedhia** [perfectsense/brightspot-cms#1149]
I am trying to create a new ContentType where the combination of Type and version needs to be unique. Example I need to be able to create objects with 

1. EmailTypeA and v1.0
2. EmailTypeA and v1.1 
3. EmailTypeB and v1.1

But not 
EmailTypeA and v1.0 again 

How do I make the combination of type and version fields unique

public class EmailTemplate extends DevZoneContent {

    @Required
    @Indexed(unique = true)
    private Set<EmailTemplateType> templateType;

    @Required
    @Indexed(unique = true)
    private String version;

    private String to;
    private String from;
}

**Comment by rhino88** [comment]
Hi zalakdedhia,

To implement a compound key, you can `@Index` a method with `unique=true`. Here is a simple example:

```
public class Foo {

    private String bar;
    private String baz;

    @Indexed(unique = true)
    public String getCompoundKey() {
        return bar + baz;
    }
}
```
