### ISSUE TITLE
CSS issue on the admin side

### ISSUE THREAD

**Issue by maiahariton** [perfectsense/brightspot-cms#1157]
Hi, 
I am new to this platform, I mistakenly added css in the admin settings and now all of the css is broken on the admin side and I don't know how to fix it.

**Comment by rhino88** [comment]
Hi Maia,

You can solve this running a simple script in the Code Playground tool provided at `/_debug/code`.

Here is a snippet you can execute to reset your extra css field:

```
import com.psddev.dari.db.*;
import com.psddev.dari.util.*;
import com.psddev.cms.tool.*;
import internal.*;
import java.util.*;
import model.*;

public class Code {
    public static Object main() throws Throwable {
        CmsTool tool = Query.from(CmsTool.class).first();
        tool.setExtraCss(null);
        tool.save();
        return "saved";
    }
}


```
