### ISSUE TITLE
Proposal: Documentation enhancements via pull requests?

### ISSUE THREAD

**Issue by Typografikon** [perfectsense/brightspot-cms#1159]
Hi to all, it will be nice to be able to sent pull requests targeted to documentation improvements. 

This is because these github issues covers many questions not mentioned in documentation so user have to search both documentation and github issues.

Is there some chance to introduce this kind of pull requests?

**Comment by rhino88** [comment]
Hey Ondřej,

We have a team dedicated to working on documentation. Our team's first goal is to revisit and restructure the existing documentation to better facilitate learning and discovery. A parallel effort is ongoing to provide a better [example project](https://github.com/perfectsense/brightspot-tutorial) for demonstrating the capabilities of Brightspot. 

Documentation updates are made via PRs to this repository by members of our team, and we may open up this process to the public at a later point in time.

For the time being, feel free to suggest updates as Github issues, and we will certainly take them into account while making changes.

Thanks for the suggestion!
