### ISSUE TITLE
StorageItem field gets cleared after object that has been copied in CMS UI gets published.

### ISSUE THREAD

**Issue by detec** [perfectsense/brightspot-cms#1243]
Steps to reproduce

1. Create class with content similar to
`public class Event extends Content {
    private StorageItem eventBanner;
}`
2. Add new Event instance in CMS, fill its eventBanner field, hit "Publish".
3. Try to copy item published at step 2. 
![copy-button-cms-ui](https://cloud.githubusercontent.com/assets/7873315/23853987/ed5644b2-07f7-11e7-8492-4ca923dbdd39.png)
4. See that visually eventBanner is filled with image (but when you put in debugger a breakpoint in beforeSave() method - you will see that eventBanner=null).
5. Hit "Publish" for the copied item and after page reloads you will see that eventBanner has cleared out.

Issue has been reproduced in different environments for different content types. When you manually add image to the copied item - it gets saved. 

Brightspot CMS version

>     <parent>
        <groupId>com.psddev</groupId>
        <artifactId>dari-parent</artifactId>
        <version>3.2.2296-735dce</version>
    </parent>

com/psddev/cms-tool-ui/3.2.6400-a25a65/cms-tool-ui-3.2.6400-a25a65.war

**Comment by rhino88** [comment]
It looks like this issue has been fixed in the latest releases:

Dari: 3.2.2422-501a79
CMS: 3.2.6985-e7140a

Are you able to upgrade to these releases?

I am going to close this issue for now, but feel free to reopen if you are experiencing issues with the latest releases.
