### ISSUE TITLE
How to install Brightspot's CMS in OSGi environment

### ISSUE THREAD

**Issue by DevDh** [perfectsense/brightspot-cms#126]
Hello,

How to run Brightspot CMS inside Osgi ?

I am trying to install the Brightspot's CMS to AEM Felix ( OSGI platform).

So, I start with cms-tools-ui war, and created the bundle to include the requirement Manifest.mf (OSGI-fy)

While installing it to OSGi, it is not making any error or warning, but when the request is received, it is not handling the request at all. Here is what I started with:
http://localhost:4502/cms

Installing logs:
telnetconsole.shell remote=/127.0.0.1:55772] org.ops4j.pax.web.service.internal.HttpServiceFactoryImpl Binding bundle: [Brightspot cms [417]] to http service
19.05.2015 05:54:23.769 _INFO_ [telnetconsole.shell remote=/127.0.0.1:55772] Brightspot cms Service [2897] ServiceEvent REGISTERED
19.05.2015 05:54:23.776 _INFO_ [pool-24-thread-1] org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper will add org.apache.jasper.servlet.JasperInitializer to ServletContainerInitializers
19.05.2015 05:54:23.777 _INFO_ [pool-24-thread-1] org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper Skipt org.apache.jasper.servlet.JasperInitializer, because specialized handler will be present
19.05.2015 05:54:23.779 _INFO_ [pool-24-thread-1] org.ops4j.pax.web.service.jetty.internal.HttpServiceContext registering context WebAppHttpContext{Brightspot cms - 417}, with context-name: cms

**Comment by rhino88** [comment]
Installing Brightspot to an OSGi environment is not currently supported, but I've opened an internal ticket. We may decide to support this at some point in the future, but it is not currently on the roadmap.
