### ISSUE TITLE
Probably BUG: Java image editor creates big png images from my small jpg files.

### ISSUE THREAD

**Issue by Typografikon** [perfectsense/brightspot-cms#1263]
Hi to all, 

after some troubles with JavaImageServlet + JavaImageEditor ( see #323) I found another **strange  behaviour**: 

After uploading jpg file via cms administration I got big png file on my website.

My setting for image size is:

![snimek obrazovky 2017-03-24 v 16 00 42](https://cloud.githubusercontent.com/assets/13291261/24299952/1403c100-10ab-11e7-95b8-dd4f3018e50c.png)

I download resulting image:

> $ curl http://devel.zlutakarta.cz/_image/3cb5e27/2147483647/thumbnail/1200x450%5E/resize/1200x450%5E/?url=http%3A%2F%2Fdevel.zlutakarta.cz%2Fstorage%2F2f%2Fd3%2Fc8e21ec24d4d849e9e073f904197%2Fresizes%2F1500%2Fdsc-0652.JPG > result.dat

Check mime types:

> $ file -i *
> dsc-0652.JPG: image/jpeg; charset=binary
> result.dat:   image/png; charset=binary

And check also dimensions:

> $ identify *
> dsc-0652.JPG JPEG 2048x1360 2048x1360+0+0 8-bit sRGB 909KB 0.040u 0:00.030
> result.dat[1] PNG 1200x450 1200x450+0+0 8-bit sRGB 998KB 0.000u 0:00.000

Check file sizes:

> $ ls -sh1
> 888K dsc-0652.JPG
> 976K result.dat

So my result is uselles - too big filesize with bad format! Any idea hot to fix it?

With best regards,
O.

**Comment by Typografikon** [comment]
Any suggestions for this issue?

How to reproduce:

> mvn archetype:generate -B -DarchetypeRepository=https://artifactory.psdops.com/psddev -DarchetypeGroupId=com.psddev -DarchetypeArtifactId=cms-app-archetype -DarchetypeVersion=3.2.6985-e7140a -DgroupId=test -DartifactId=test-brightspot -DmodelVersion=1.0-SNAPSHOT

Create image entity:

```java
package test;

import com.psddev.cms.db.Content;

import com.psddev.cms.db.ToolUi.*;
import com.psddev.cms.db.Renderer.*;
import com.psddev.dari.db.Recordable.*;

import com.psddev.dari.util.StorageItem;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * {@link Image} represents simple image.
 */

@Path("/WEB-INF/jsp/image.jsp")
@PreviewField("file")
@DisplayName("Image")
@Note("Simple image")
public class Image extends Content {

	@Ignored
	protected Logger logger = LoggerFactory.getLogger(getClass());

	@Indexed
	@Required
	@Filterable(false)
	@Tab("Main")
	@DisplayName("Image file")
	protected StorageItem file;

	/* overrides */

	@Override
	public String getLabel() {
		return getClass().getSimpleName() + "-" + getId();
	}

	/* generated */

	public StorageItem getFile() {
		return file;
	}

}

```

Create /WEB-INF/jsp/image.jsp:

```jsp
<%@page contentType="text/html; charset=UTF-8" %>
<%@ taglib prefix="c"   uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn"  uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="cms" uri="http://psddev.com/cms" %>

<cms:img class="" src="${content}" title="${content.label}" size="TestSize" />
```

Set styleguide.viewgenerator.skip to true in pom.xml:

```xml
...
<styleguide.viewgenerator.skip>true</styleguide.viewgenerator.skip>
...
```

Start project:

> touch undefined.js
> mvn -P run clean package cargo:run

Create TestSize in Standard Image Sizes in cms settings:

![snimek obrazovky 2017-04-04 v 14 53 53](https://cloud.githubusercontent.com/assets/13291261/24657444/9208a270-1946-11e7-8602-bf76e3146c81.png)

Create Image instance using file from attachement and set /image.html as URL:

![snimek obrazovky 2017-04-04 v 14 55 43](https://cloud.githubusercontent.com/assets/13291261/24657514/ce97de54-1946-11e7-916b-a578bd17a865.png)

Go to the browser, type http://localhost:9480/image.html and check image, you will see 1.03 MB PNG image (1200x450) - compare with 853 kB jpg file DSC_0725.JPG (2048x1360).

![dsc_0725](https://cloud.githubusercontent.com/assets/13291261/24657524/df0e155a-1946-11e7-8b8d-2cf3f6e02724.JPG)

Any **fix is highly needed** :-)

Best regards, 
Ondrej.

**Comment by rhino88** [comment]
Thanks for reporting this Ondrej, we have someone working on this and will get this fixed as soon as we can. The internal ticket is BSP-3277

**Comment by Typografikon** [comment]
It's great - thanks for response! When fix will be available I test it to confirm it works fine in my project. O.

**Comment by rhino88** [comment]
@Typografikon the fix for this issue has been merged into dari and is available by updating your dari dependency to`3.2-SNAPSHOT`. It will also be included in the next patch release (Patch Release #12).

**Comment by Typografikon** [comment]
Great news!

I updated dependency to 3.2-SNAPSHOT but I didn't see related changes in JavaImageServlet https://github.com/perfectsense/dari/pull/298/commits/5da9b752543ccf77d8274ef6a6d722cc4c5bb04f 

I use repository https://artifactory.psdops.com/public and:

- with 3.2-SNAPSHOT dependency `dari-image-3.2-20170222.161235-128.jar` is used and 
- with 3.3-SNAPSHOT `dari-image-3.3-20170424.162052-18.jar` is used but still without fix included

Can you help?

**Comment by Typografikon** [comment]
Still cannot get fixed version from maven repos. Cannot understand whats is wrong?!

Any help appreciated. Thanks!
