### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by candrews** [perfectsense/brightspot-cms#1268]
README.md says:
> Brightspot is open-source and freely available for use under the GNU GENERAL PUBLIC LICENSE V2.

But it also says:
> Brightspot is released under the AGPLv3 license.

The LICENSE file is the GPLv2 license.

So I assume the license is GPLv2, but it would be great to fix these inconsistencies.

**Comment by rhino88** [comment]
Thanks for catching that, we recently updated the license in the readme and missed the second mention.

PR is open to address this: https://github.com/perfectsense/brightspot-cms/pull/1270
