### ISSUE TITLE
brithgspot quick install error - Could you please help !!

### ISSUE THREAD

**Issue by Krish336** [perfectsense/brightspot-cms#1271]
Downloaded: https://repo.maven.apache.org/maven2/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar (276 KB at 6723.3 KB/sec)
 _____ _____ _____ _____ _____ _____ _____ _____ _____ _____
| __  | __  |     |   __|  |  |_   _|   __|  _  |     |_   _|
| __ -|    -|-   -|  |  |     | | | |__   |   __|  |  | | |
|_____|__|__|_____|_____|__|__| |_| |_____|__|  |_____| |_|
 _____ _              _____                     _
|  |  |_|___ _ _ _   |   __|___ ___ ___ ___ ___| |_ ___ ___
|  |  | | -_| | | |  |  |  | -_|   | -_|  _| .'|  _| . |  _|
 \___/|_|___|_____|  |_____|___|_|_|___|_| |__,|_| |___|_|

Scanning Directory C:\brightspot\brightspot-tutorial\target\tutorial-1.0-SNAPSHOT
Found 12 errors in 4 JSON files:

    node_modules\tutorial\styleguide\_wrapper.json has 6 errors:
        External template reference. [/node_modules\tutorial\styleguide\content\page\Page.hbs] refers to a path outside of the base directory. at (line=2, col=41, offset=42)
        Could not resolve template path [/node_modules\tutorial\styleguide\content\page\Page.hbs] at (line=2, col=41, offset=42)
        Couldn't find _dataUrl: /node_modules\tutorial\styleguide\content\page\PageFooter.json at (line=11, col=51, offset=267)
        Must specify the view via the _view key or _template key! at (line=10, col=16, offset=216)
        Couldn't find _dataUrl: /node_modules\tutorial\styleguide\content\page\PageHeader.json at (line=5, col=51, offset=146)
        Must specify the view via the _view key or _template key! at (line=4, col=16, offset=95)

    node_modules\tutorial\styleguide\content\page\PageHeader.json has 2 errors:
        External template reference. [/node_modules\tutorial\styleguide\content\page\PageHeader.hbs] refers to a path outside of the base directory. at (line=2, col=34, offset=35)
        Could not resolve template path [/node_modules\tutorial\styleguide\content\page\PageHeader.hbs] at (line=2, col=34, offset=35)

    node_modules\tutorial\styleguide\content\page\PageFooter.json has 2 errors:
        External template reference. [/node_modules\tutorial\styleguide\content\page\PageFooter.hbs] refers to a path outside of the base directory. at (line=2, col=34, offset=35)
        Could not resolve template path [/node_modules\tutorial\styleguide\content\page\PageFooter.hbs] at (line=2, col=34, offset=35)

    node_modules\tutorial\styleguide\content\article\Article.json has 2 errors:
        External template reference. [/node_modules\tutorial\styleguide\content\article\Article.hbs] refers to a path outside of the base directory. at (line=2, col=29, offset=30)
        Could not resolve template path [/node_modules\tutorial\styleguide\content\article\Article.hbs] at (line=2, col=29, offset=30)

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:17 min
[INFO] Finished at: 2017-03-28T15:28:27-04:00
[INFO] Final Memory: 25M/136M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.psddev:styleguide-maven-plugin:2.0-SNAPSHOT:generate-views (default) on project tutorial: Execution default of goal com.psddev:styleguide-maven-plugin:2.0-SNAPSHOT:generate-views failed:
[ERROR] Failed to generate view classes due to 12 previous errors.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by danslaughter2** [comment]
Closing as this is being tracked here instead: https://github.com/perfectsense/brightspot-tutorial/issues/3
