### ISSUE TITLE
Lack of documentation on how to reset authentication code

### ISSUE THREAD

**Issue by artemik** [perfectsense/brightspot-cms#1313]
For two factor authentication code there is this line in the docs:

> If you lost the device with the authenticator app, ask your Brightspot developer to reset the authentication code.

But where and how do I reset this authentication code?

**Comment by rhino88** [comment]
Hi artemik,

We recently updated the documentation to include a new FAQ section which should answer your question:

http://docs.brightspot.com/cms/developers-guide/faqs/reset-tfa.html

**Comment by artemik** [comment]
Thanks, great.

Please, at this page (http://docs.brightspot.com/cms/editorial-guide/two-factor-auth/index.html) make a link leading to the page you provided. I couldn't find it, Google didn't help.
