### ISSUE TITLE
Dynamic scheduled job 

### ISSUE THREAD

**Issue by ajayaks** [perfectsense/brightspot-cms#153]
Hi,

Is there any way we can create scheduled job which reads data from file at runtime and execute accordingly.

Actually instead of creating job for each operation where only _id or _type is varying , what is the preferred way for creating dynamic job?
Please suggest.

Regards
Ajay

**Comment by Ryan-Anderson** [comment]
Take a look at `RepeatingTask` found here:

https://github.com/perfectsense/dari/blob/master/util/src/main/java/com/psddev/dari/util/RepeatingTask.java

I think this should cover your use case.

**Comment by ajayaks** [comment]
Thanks for you response Ryan but i m looking for below.

When we configure job in CMS we define class, the schedule etc but there is no way we can pass some file or input arguments to the job which can be read during execution.

Scheduling the job is not problem but how to execute that job on different content type is a requirement.
Please suggest.

**Comment by Ryan-Anderson** [comment]
Perhaps [AsyncConsumer(https://github.com/perfectsense/dari/blob/master/util/src/main/java/com/psddev/dari/util/AsyncConsumer.java) would fit your use case? This allows you to process a queue on a background thread.

Alternatively, you may want to look into using a message queuing service such as Amazon SQS or Rabbit MQ.

**Comment by Ryan-Anderson** [comment]
Closing this issue for now. Please let us know if you have any additional questions!
