### ISSUE TITLE
Title field of an SEO object associated with a Content object using @Content.LabelFields

### ISSUE THREAD

**Issue by tankchintan** [perfectsense/brightspot-cms#165]
_NOTE_: Copied this from https://github.com/perfectsense/dari/issues/79 since this repostiory seems to be a better place for this issue.

---

Hi I have never seen this behavior before from SEO object.

We have a `Content` class called as `Professor` & in the CMS when we edit this object we can see the "Search Engine Optimization" to be completely empty for `title` & `description`.

I have also annotated `Professor` with `@Content.LabelFields`.

Currently when I spit out `${seo.title}` in my JSP it comes out to be this above `@Content.LabelFields` as opposed to empty string, which I was expecting.

Thing is we have a workflow in our system which looks for `seo.title` & if it's empty it looks for alternative **correct** value.

But since `seo.title` is not empty I am getting wrong values for some of the markup.

So essentially, I want to use `seo.title` only when it is curated by some human & not the dynamically generated `content.label`.

And I want to give preference to `seo.title` when curated by human, even over the method we have in place for dynamically calculating the title.

**Comment by rhino88** [comment]
Hi tankchintan,

Your use case can be solved by using the [SEO annotations](https://github.com/perfectsense/brightspot-cms/blob/release/3.2/db/src/main/java/com/psddev/cms/db/Seo.java#L468) which allow you to perform your own business logic as a fallback for the SEO values

Example:

```

@Seo.TitleFields("getSeoTitle")
public class Article extends Content {

    private String title;

    @ToolUi.Hidden
    @Ignored(false)
    public String getSeoTitle() {
        String seoTitle = this.as(Seo.ObjectModification.class).getTitle();
        if (StringUtils.isBlank(this.as(Seo.ObjectModification.class).getTitle())) {
            seoTitle = // your dynamically produced SEO title;
        } else {
            seoTitle = this.as(Seo.ObjectModification.class).getTitle();
        }
        return seoTitle;
    }
}

```

I'm going to go ahead and close this issue, but feel free to reopen if this does not satisfy your requirements.
