### ISSUE TITLE
Prevent Deletion

### ISSUE THREAD

**Issue by KodakAlarisUser** [perfectsense/brightspot-cms#174]
Is there a way to prevent a user from deleting specific content?

**Comment by Ryan-Anderson** [comment]
Currently permission to delete content is tied to "Publish" permissions for a given type. So allowing a role to publish content also gives them the ability to delete.

![image](https://cloud.githubusercontent.com/assets/1299507/8186963/3dd5d90c-141b-11e5-88f6-1ee7880a45aa.png)

**Comment by Ryan-Anderson** [comment]
Also, you could override `beforeDelete()` and throw an exception if delete should not be permitted.

**Comment by KodakAlarisUser** [comment]
Great!  We'll give that option a try.  Thanks.

**Comment by Ryan-Anderson** [comment]
We've added Content Delete permissions in PR #225. If you are using v 3.1+ you can use this to configure your delete permissions.
