### ISSUE TITLE
Content field null after setting value of it to new Content in workflow

### ISSUE THREAD

**Issue by KodakAlarisUser** [perfectsense/brightspot-cms#183]
I have something similar to the following:

public class Bar extends Content
{
    ...
}

public class Foo extends Content
{
    ...
    private Bar b;
    ...
}

And Bar is set to move through a workflow, where the first Status is "Pending".  If I create a new Bar via the UI, move it through to the Pending status, set it on a published instance of Foo, and inspect the Foo instance, it's b field is null.  I need to be able to query for Foo and fetch any of it's properties that are in a Pending status.  How can this be achieved?

**Comment by danslaughter2** [comment]
When fetching Foo via Query API, also call `resolveInvisible()`.

Ex. `Foo foo = Query.from(Foo.class).resolveInvisible().first();`

Then when you call `foo.getBar()` it should resolve.

**Comment by KodakAlarisUser** [comment]
Thanks!  Work's beautifully!
