### ISSUE TITLE
Is it possible to set an `Modification` on a `Site` directly?

### ISSUE THREAD

**Issue by tankchintan** [perfectsense/brightspot-cms#186]
I have a `Modification` on the dari `Site` class called `ExtendedSiteConfig`. I was wondering if I can directly set an instance of a `ExtendedSiteConfig` on a particular `Site` via a setter or something similar?

**Comment by Ryan-Anderson** [comment]
I think what you are looking for is `site.as(ExtendedSiteConfig.class)`, this will return an instance of the `ExtendedSiteConfig` linked to your `Site` object.

**Comment by tankchintan** [comment]
Not quite.

I know how to retrieve a modification instance.

What I want to know is, how to set an instance of a modification class (`ExtendedSiteConfig`) directly on to the parent class `Site`.

Are you saying do something like,

```
ExtendedSiteConfig newExtendedSiteConfig = new ExtendedSiteConfig();
//...

ExtendedSiteConfig currentExtendedSiteConfig = site.as(ExtendedSiteConfig.class);

currentExtendedSiteConfig = newExtendedSiteConfig;

currentExtendedSiteConfig.save();

site.save();
```

**Comment by Ryan-Anderson** [comment]
You don't do this explicitly. Dari takes care of saving the Modification fields to the state of the modified object for you.

Do you have a particular use case in which the default behavior is not suitable?

**Comment by tankchintan** [comment]
So I have an API that is used to update/replace/create the existing `ExtendedSiteConfig` value for a `Site`.

I will create the new `ExtendedSiteConfig` using the input I get from the API. But then how do I save this to the appropriate instance of `Site` is my question.

Also I use the Gson serializer to automatically create the instance of `ExtendedSiteConfig` form json input.

**Comment by Ryan-Anderson** [comment]
Based on what you are trying to accomplish, [State.linkObject()](https://github.com/perfectsense/dari/blob/master/db/src/main/java/com/psddev/dari/db/State.java#L115) is the right api for your use case.

You can link your `ExtendedSiteConfig` to the state of your `Site`.

However, it would be more efficient to read your json parameters yourself, and call the individual setters on your Modification object directly.

**Comment by tankchintan** [comment]
Hmm. Ok. 

So `site.getState().linkObject(extendedSiuteConfig)` ?

**Comment by Ryan-Anderson** [comment]
Closing this issue, as I think you have a handle on the solution.

Let us know if you have additional questions.
