### ISSUE TITLE
Secure session cookies

### ISSUE THREAD

**Issue by markpfletcher** [perfectsense/brightspot-cms#188]
Are there any issues with setting Secure and HttpOnly flags for session cookies on brightspot cms?

**Comment by hyoolim** [comment]
No, there are no issue sending the cookies with those settings. This is on our list of todos, but we haven't made the change yet. Are you asking us to add it to a specific version?

**Comment by markpfletcher** [comment]
We are currently using v2.4, it would be great if it could be added to the next minor release.

**Comment by rhino88** [comment]
Resolved by https://github.com/perfectsense/brightspot-cms/commit/c6973286af6cd4331a81c50a945bc5d827a0bda3
