### ISSUE TITLE
Hierarchical structure (tree) and howto work with it in cms gui?

### ISSUE THREAD

**Issue by Typografikon** [perfectsense/brightspot-cms#246]
Hi,

I have now another question - how to model tree structure and work with it in cms gui? I want to have folder tree and assign articles into it (so folders are hierarchical containers for articles). Basically parent property in Folder class should be enough to reailze this, but problem is with cms qui - it looks like that cms can display only flat list of items so there is no easy way how to find some folder. Miss I something?

Best regards,
Ondrej.

**Comment by ryanhaber** [comment]
Example of class Folder with a list of folders inside, as well as a list of
articles.

On Fri, Jul 24, 2015 at 2:47 PM, Ondřej Němeček <notifications@github.com>
wrote:

> Hi,
>
> I have now another question - how to model tree structure and work with it
> in cms gui? I want to have folder tree and assign articles into it (so
> folders are hierarchical containers for articles). Basically parent
> property in Folder class should be enough to reailze this, but problem is
> with cms qui - it looks like that cms can display only flat list of items
> so there is no easy way how to find some folder. Miss I something?
>
> Best regards,
> Ondrej.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/perfectsense/brightspot-cms/issues/246>.
>



-- 

Ryan Haber
Technical Writer / Documentation
Perfect Sense

**Comment by ryanhaber** [comment]
Oops. Ignore the last one.

On Fri, Jul 24, 2015 at 3:58 PM, Ryan Haber <rhaber@perfectsensedigital.com>
wrote:

> Example of class Folder with a list of folders inside, as well as a list
> of articles.
>
> On Fri, Jul 24, 2015 at 2:47 PM, Ondřej Němeček <notifications@github.com>
> wrote:
>
>> Hi,
>>
>> I have now another question - how to model tree structure and work with
>> it in cms gui? I want to have folder tree and assign articles into it (so
>> folders are hierarchical containers for articles). Basically parent
>> property in Folder class should be enough to reailze this, but problem is
>> with cms qui - it looks like that cms can display only flat list of items
>> so there is no easy way how to find some folder. Miss I something?
>>
>> Best regards,
>> Ondrej.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/perfectsense/brightspot-cms/issues/246>.
>>
>
>
>
> --
>
> Ryan Haber
> Technical Writer / Documentation
> Perfect Sense
>



-- 

Ryan Haber
Technical Writer / Documentation
Perfect Sense

**Comment by Ryan-Anderson** [comment]
HI Ondrej,

We find that a typical pattern for creating a hierarchy of Articles is to apply Tags or Categories from a taxonomy.An example implementation might involve a `Tag` model, which implements the Brightspot [Taxon](https://github.com/perfectsense/brightspot-cms/blob/master/db/src/main/java/com/psddev/cms/db/Taxon.java) interface. Here is an example for you:

```

public class Tag extends Record implements Taxon {

    @Required
    @Indexed
    private String name;

    @Indexed
    private Tag parent;

    @Indexed
    @Recordable.JunctionField("parent")
    private List<Tag> children;

    public Tag getParent() {
        return parent;
    }

    public void setParent(Tag parent) {
        this.parent = parent;
    }
    
    @Override
    public boolean isRoot() {
        return getParent() == null;
    }

    // Getters and Setters...

}
```


Implementing the Taxon interface will provide you with a tree view of your `Tag` taxonomy:

![image](https://cloud.githubusercontent.com/assets/1299507/9584826/71685996-4fe1-11e5-8b4f-4c59b464d1ee.png)

Once you've created a `Tag` or other `Taxon` model, add field(s) to your `Article` model that will allow them to represent their appropriate location in a hierarchy.  For example:

```
public class Article extends Content {

private String title;
private ReferentialText body;
private List<Tag> tags;

// Getters and Setters...

}
```

With this approach, Articles can be organized in the hierarchy, based on the presence of tags or other taxonomies.

Let us know if you have additional questions!

**Comment by Typografikon** [comment]
Many thanks for perfect answer! Some time before I noted Tag class here [rustytanton/brightspot-base-test](https://github.com/kluman/brightspot/blob/master/src/main/java/com/kluman/Tag.java) and here [kluman/brightspot](https://github.com/rustytanton/brightspot-base-test/blob/master/src/main/java/com/brightspotbase/Tag.java) but I didn't figure out that it's related to my issue (which is tree structure). 

So it looks like Taxon interface match my needs - specially nice cms ui rendering. But two questions still remains:

1. **How to manually sort Tag's** (let's say Music, Film and Literature) and also **how to manually sort Articles with some Tag** (let's say some Books with Literature Tag)? Is it possible to do it by Drag and Drop in cms ui or something similar? 

   We can maybe consider simplified case when Article can has only one Tag (because with more tags 
   we fall in more difficulties...):

   ```java
   public class Article extends Content {

   private String title;
   private ReferentialText body;
   private Tag tags;
   
   // Getters and Setters...
   
   }
   ```
   I already asked in #275 issue where I write more about my troubles with JunctionField and sorting.

2. And additional (hope simple) question: It is possible to **render Article in various page layouts depending on assigned Tag**? Consider that Article can have only one Tag. 

   For example: How to use different page layout for Music and Literature? I didn't mean different rendering of Article content itself which can be reached by using [Contextual Rendering](http://www.brightspot.com/docs/3.0/templating/contextual-rendering?highlight=context) 

   I know I can create different Article class for each layout I want to use (and set different @Renderer.LayoutPath). I can also put some switch in main layout jsp, but ... - which is best way to do it? 

Best regards,
Ondrej.

**Comment by Typografikon** [comment]
Update:  Question 1. **How to manually sort Tag's** is answered because @JunctionField can be sorted in latest snapshot version, see #275 

So still remains only question 2. **How to render Article in various page layouts depending on assigned Tag**. Which is best way to do it?

**Comment by rhino88** [comment]
@Typografikon I'm not sure if you have already discovered a solution to question number 2 or not. If you are still looking for a solution, we recommend you take a look a [Contextual Rendering](http://www.brightspot.com/docs/3.0/templating/contextual-rendering) in the documentation.

Here is a simple example for implementing contextual rendering based on tag name.

**Article Model**

```@Renderer.LayoutPath("/WEB-INF/content/layout.jsp")
@Renderer.Paths({
        @Renderer.Path(value="/content/article/sports.jsp")
        @Renderer.Path(context = "sports", value="/content/article/sports.jsp"),
        @Renderer.Path(context = "news", value="/content/article/news.jsp")
})
public class ContextualArticle extends Content {

    private String title;
    private ReferentialText body;
    private Tag tag;

    /* Getters and Setters */
}
```

**Tag Model**

```
public class Tag extends Content implements Taxon {

    private String name;

    public String getContext() {
      return name;
    }
}
```

**Layout Renderer**

```
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="cms" uri="http://psddev.com/cms" %>
<html>
<head>
    ...
</head>
<body>

<%-- Render Common Header --%>

<cms:render context="${mainContent.tag.context}" value="${mainContent}"/>

<%-- Render Common Footer --%>

</body>
</html>
```

With this implementation, the layout renderer would delegate to the contextual renderer based on the name of the tag. This could be enhanced to return an editorial value, simply by adding a `context` field to `Tag`, or something similar.

The `@Renderer.Path` annotation without a `context` would act as a default, if a contextual rendering path was not found on the `Article`.

I will go ahead and close this issue for now, but let us know if you have additional questions around this. Thanks!

**Comment by Typografikon** [comment]
Many thanks for response and detailed sample code. I already discovered  contextual rendering and I use it with success. I believe your answer can be useful for other developers.
