### ISSUE TITLE
How to deal with multiple modules on one page?

### ISSUE THREAD

**Issue by Typografikon** [perfectsense/brightspot-cms#263]
Hi to all, 

I study Hello world example http://www.brightspot.com/docs/3.0/overview/hello-world#render-content 

I understand that any content type can be used to render page and I understand that content type instance is activated by its url. So when I hit url of some Article, appropriate instance is found and rendered via @Renderer.Path jsp. But what should I do when I want to show more items on page? For example I want:

1. article content (=article detail)
2. other articles links (=article list) 
3. events in calendar (=not related to any article)

Should I add these getters to Article class - even if Event is not related to any Article?

```java
public class Article extends Content {
   public List<Article> getArticles(){
      return Query.from(Article.class).selectAll();
   }
   public List<Event> getEvents(){
      return Query.from(Event.class).selectAll();
   }
}
```

Because there is no controllers in Brightspot CMS I misunderstood content types concept. Is content type model for Article records itself or model for page which renders Article records? Please, clarify this. 

Many thanks,
Ondrej.

**Comment by Typografikon** [comment]
Any comment on this issue will be highly appreciated...

**Comment by hyoolim** [comment]
Yes, our current practice is to add those methods to the Article class directly, or create a helper class that can be accessed from Article:

```
public class Article extends Content {
    public ArticleView getView() {
        return new ArticleView(this);
    }
}

public class ArticleView {

    private Article article;

    public ArticleView(Article article) {
        this.article = article;
    }

    public List<Event> getEvents() {
        return Query.from(Event.class).where("parent = ?", article).selectAll();
    }
}
```

We are actually working on something more formal for the 3.1 release, and you can see its progress at https://github.com/perfectsense/brightspot-cms/pull/261

**Comment by Typografikon** [comment]
Thanks for excellent response a pointing me to pr #261
