### ISSUE TITLE
Translation/localization

### ISSUE THREAD

**Issue by Typografikon** [perfectsense/brightspot-cms#264]
Two simple questions: 

1. Can be content type fields translated? I want to have *title* property and getters in class but  translated field name *Titulek* in cms backend ui (= translation to czech language). Is it possible?

   Cms backend ui:

   ![cms-titulek-01](https://cloud.githubusercontent.com/assets/13291261/9289333/21d09ba4-436c-11e5-85dd-a62979b2f0ba.png)

   Class:

   ```java
public class Article extends Content {

	@Required
	@Indexed
	@ToolUi.Note("Hlavní titulek článku")
	String title; //<-- how to name it "Titulek" in cms ui?

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
}
```

2. Can be translated build-in strings in cms ui itself? I want czech button labels, Publikovat instead of Publish, Vítejte instead of Welcome etc. Is it possible?

**Comment by danslaughter2** [comment]
1. Yes, using the `@DisplayName` annotation on the field.

2. Partially, you can alter the Publish button text specifically using `@ToolUi.PublishButtonText` on the content type for which you want it to be different.  If you want it on ALL content types, then you can either a) Add the annotation to all types, or b) create a common parent class and add it there. As for other UI elements, we are in the process of localizing the CMS UI at large.

**Comment by Typografikon** [comment]
Thanks, @DisplayName annotations works great for both fields and classes. 

About localizing the CMS UI - my concern is not only publish button, but also other texts in cms ui. Is there change to localize all texts? Or most of them? I usually found .properties file for this in java programs, is there something similar? I take a quick look on brighstspot sources and found a lot of texts hardcoded in jsp or java classes...

**Comment by danslaughter2** [comment]
Localization of the other texts in the CMS UI is still in development, so not yet available.

**Comment by Typografikon** [comment]
Thanks for response.
