### ISSUE TITLE
Is there release plan for brightspot-cms?

### ISSUE THREAD

**Issue by Typografikon** [perfectsense/brightspot-cms#269]
Hi, I ask some questions #263  #264 and answer was „it is work in progress“. Is there some release plan: which features are planned for which version and supposed release date? It help me to manage project... 

Thanks for response.

**Comment by Typografikon** [comment]
I must repeat this question. There is no point to explain which releases/version are stable and there is no explanation about dari versus cms versioning (relation between dari and cms versioning).

Features plan should be also useful.

**Comment by Ryan-Anderson** [comment]
Hey Ondrej, apologies for the slow reply. 

With past releases, we have had a very loose release schedule. For future releases, we are transitioning to a faster release cycle, where we will have a new release every 6-8 weeks. Going forward, each release will be accompanied by release notes which you can find here: https://github.com/perfectsense/brightspot-cms/releases

As for the version compatibility, we aim to keep dari/brightspot on parallel versions. So 3.1x in dari should be used with 3.1x in Brightspot. With every version, we also will update the maven archetype with the newest Dari and Brightspot dependencies.

**Comment by Ryan-Anderson** [comment]
Closing this issue. Please let us know if you have any additional questions.

**Comment by Typografikon** [comment]
Thanks for exhaustive response. I suggest place your explanation also on brightspot website so other developers can know it.
