### ISSUE TITLE
How to order items manually when JunctionField and JunctionPositionField are used

### ISSUE THREAD

**Issue by Typografikon** [perfectsense/brightspot-cms#275]
Is there some way how to sort **manually** items when autopopulated via JunctionField annotation? I mean ordering items manually in the same way as List<Content> without  Junction* annotation can be sorted.

**Example 1**: Let's consider Video and Playlist below. Can be orderNo automatically updated when change videos ordering via drag and drop in Playlist? 

```java
public class Video extends Content { 

    private String name;
    private Integer orderNo;
    private StorageItem videoFile;

    @Indexed 
    private Playlist playlist; 
} 

public class Playlist extends Content { 

    private String name; 

    @Indexed 
    @Recordable.JunctionField("playlist") 
    @Recordable.JunctionPositionField("orderNo")
    private List<video> videos; 
} 
```

**Example 2**: Let's consider the same example as above but without orderNo. Can be ordering information saved somewhere in Dari internal metada?

**Comment by Typografikon** [comment]
Any ideas on this question will be highly appreciated. I need to build tree structure (as mentioned also here #246) and I wonder how to conceptualize it. Basically I need manually-sortable items in tree and I need also ability to evaluate branch in tree (= path from leaf to the main root of tree - analogous to directory path on filesystem).

When only Lists without Junction* can be sorted manually in cms administration ui than I cannot build manually sortable tree structure using **parent reference** so I must build tree structure using **list with childs** reference. But in this case one child can be contained in many parents so I can find multiple paths to some item. How to deal with it? Compare variants 1 and 2 below.

**1. Variant with parent**: not manually sortable but path to the root can be evaluated

```java
public class Item extends Content { 

    @Indexed
    private String name;

    @Indexed
    private Item parent; 
} 
```

**2. Variant with childs list**: manually sortable but path to the root cannot be evaluated

```java
public class Item extends Content { 

    @Indexed
    private String name;

    @Indexed
    @ToolUi.FieldSorted
    private List<Item> childs; 
} 
```

Really \*thanks\* for any comment!

**Comment by Typografikon** [comment]
I investigated this issue and it looks **like a bug**, because I checked [AbstractDatabase.saveJunctions](https://github.com/perfectsense/dari/blob/06bdc77c99a5c1a6a51f2b5e6ed245b498485cea/db/src/main/java/com/psddev/dari/db/AbstractDatabase.java#L122) and it should probably work as follows:

```java
@ToolUi.DefaultSortField("orderNo") //<-- to see video search results sorted by orderNo
public class Video extends Content { 

    @Indexed
    private Integer orderNo;

    @Indexed 
    private Playlist playlist; 
} 

public class Playlist extends Content { 

    @Indexed 
    @ToolUi.FieldSorted // <-- enable sorting in edit form
    @Recordable.JunctionField("playlist")  // <-- join via Video.playlist field
    @Recordable.JunctionPositionField("orderNo") // <-- apply sorting to Video.orderNo after safe
    private List<Video> videos; 
}
```

When tested this some numeric values are propagated to `Video.orderNo` but **not reflecting position** in `Playlist` editation form. I try `String`, `double` and `Integer` for `orderNo` but without success. For 3 items in videos list I got 1.1, 0.1 and -1.0 as `orderNo` values.

Any ideas how to resolve it?

**Comment by Typografikon** [comment]
**Problem solved!** After upgrading to **3.1-SNAPSHOT** all works as described above. Version 3.1-SNAPSHOT fixes problem and sorting via `@JunctionPositionField` is propagated to content field properly. Unfortunately 3.1-SNAPSHOT is not stable release so there can be other bugs...

**Upgrading** si fair simple, in pom.xml upgrade version for dari-parent, cms-db, cms-tool-ui, dari-db, dari-util and dari-reloader-tomcat6. You can also use 3.1-SNAPSHOT version of cms-app-archetype from http://public.psddev.com/maven/ archetype catalog.

After upgrade cargo plugin started application but Tomcat complains about missing async support and  also JSP page compiler failed to compile jsp because some constructs requires java 1.8 Because I have java 1.8 I only need to **change container configuration**: I modified setting in main Tomcat's web.xml to instruct JSP page compiler to use java 8 (via compilerSourceVM  and compilerTargetVM parameters) and I also upgraded application web.xml root alement to web-app version 3.0 and add <async-supported>true</async-supported> to ApplicationFilter. By default there is no web.xml in application directory tree so you need to copy one to etc directory and add as <configfile> to cargo-maven2-plugin in pom.xml. After these changes all works as usually and junction sorting finnaly works!

**Comment by danslaughter2** [comment]
@Typografikon Yes, there is a pull request out to address the cargo plugin issues. See below:

https://github.com/perfectsense/brightspot-cms/pull/279

**Comment by Typografikon** [comment]
Final conclusion: Items autopopulated via JunctionField annotation can be sortet manually by drag-and-dropping directly in cms ui, but 3.1-SNAPSHOT version is required and classes need to be annotated as described [here](https://github.com/perfectsense/brightspot-cms/issues/275#issuecomment-137569037)  There is also configuration issue when running 3.1-SNAPSHOT, see pull request #279 for more.

**Comment by Typografikon** [comment]
@danslaughter2: thnks
