### ISSUE TITLE
How to do additional processing when content is copied

### ISSUE THREAD

**Issue by KodakAlarisUser** [perfectsense/brightspot-cms#280]
We would like to do some additional processing right after a user creates a copy of a piece of content, but before a save.  Is there a hook or event we can listen for when a copy has occurred?

**Comment by Typografikon** [comment]
You can use before and after hooks from `com.psddev.dari.db.Record` like this:

```java
public class Article extends Content {

	@Override
	protected void beforeSave(){
		super.beforeSave();
		// your code
	};
}
```

Hope it match your needs.

**Comment by KodakAlarisUser** [comment]
Thanks, Typografikon.  In the beforeSave(), is there some indication/flag that the copy has occurred or that we are working with a copy?

**Comment by kphenix** [comment]
@KodakAlarisUser Are you referring to the editorial copy feature seen here?

![screen shot 2015-09-04 at 10 15 31 am](https://cloud.githubusercontent.com/assets/1231990/9685710/f5325aba-52ed-11e5-9ffb-3ca7dab2d022.png)

**Comment by KodakAlarisUser** [comment]
Yes.

**Comment by Typografikon** [comment]
No idea about it, but there is at least isNew() method, see https://github.com/perfectsense/dari/issues/53

**Comment by KodakAlarisUser** [comment]
Checking the value of isNew() in the beforeSave() may be an option if it still allows us to do something similar to the following example:

public class Foo
{
    private String name;
    ...
}

When the user selects "New > Copy This Foo", we may want to change the "name" string to "Copy Of ...".

**Comment by Typografikon** [comment]
Before- and after- hooks allows data validation and manipulation including fields population ([see docs](http://www.brightspot.com/docs/3.0/data-validation/before-save)). But you have no reference to instance from which new instance was originaly copied and there is simply no afterCopy(Record origin) hook.

**Comment by KodakAlarisUser** [comment]
We were able to manipulate field values in the beforeSave() while filtering on the value of isNew().  However, after a save, we were unable to redirect to the copied object; the view of the original remained the current view.

In the end, we went the route of creating a Filter, which is responsible for creating a copy and redirecting to it if "copyId" is in the URL.  It's a little hacky, but the only option we were able to have success in.

**Comment by rhino88** [comment]
@KodakAlarisUser We've since added the [Copyable](https://github.com/perfectsense/brightspot-cms/blob/release/3.2/db/src/main/java/com/psddev/cms/db/Copyable.java) interface in #747, and modified in #772.

Overriding `onCopy()` on your implementing class should provide you with the functionality desired. We will go ahead and close this ticket for now, but feel free to reopen if you have additional questions.
