### ISSUE TITLE
Documentation: @ToolUi.DefaultSortField is class anotation

### ISSUE THREAD

**Issue by Typografikon** [perfectsense/brightspot-cms#283]
In documentation for 3.0 version http://www.brightspot.com/docs/3.0/annotations-guide/reference-guide#p-marker23 is anotation @ToolUi.DefaultSortField described as as field anotation but it is a class anotation,  field anontation is not supported. Should be fixed.

**Comment by kphenix** [comment]
Thanks @Typografikon - Fixed

**@ToolUi.DefaultSortField**

Specifies which field should be used as the default sorter. In the example below, the headline is the default sorter for Articles:
```
    @ToolUi.DefaultSortField("headline")
    public class Article extends Content {

        private String headline;
		
	}
```

**Comment by Typografikon** [comment]
Thanks - it is nice to se documentation improvements.
