### ISSUE TITLE
Documentation: @Recordable.JunctionPositionField should be more described

### ISSUE THREAD

**Issue by Typografikon** [perfectsense/brightspot-cms#284]
Anotation `@JunctionPositionField` propagates sorting values to position fields of each instance in collection annotated via `@JunctionField` It simply overwrites its original values. This should  be mentioned in documentation http://www.brightspot.com/docs/3.0/annotations-guide/reference-guide#p-marker73 

Small example can also help to understand how to use it with @ToolUi.FieldSorted

**Comment by rhino88** [comment]
Thanks for the feedback.

We've added `@JunctionFieldPositionField` to the documentation here: http://www.brightspot.com/docs/3.2/annotations/data

`@ToolUi.FieldSorted` is mentioned here: http://www.brightspot.com/docs/3.2/annotations/ui-control
