### ISSUE TITLE
Which interfaces are supported in content fields?

### ISSUE THREAD

**Issue by Typografikon** [perfectsense/brightspot-cms#286]
All interface used as fields must extends `com.psddev.dari.db.Recordable` interface (otherwise Brightspot complains „Can't use interface“) but Brightspot also supports other interfaces as `java.util.List`, `java.util.Set` and many basic types as `java.lang.String` or `java.util.Date`.

The question is **which interfaces are currently supported**? Some generic notes are here http://www.dariframework.org/models.html but this is not comprehensive and developer should be able to check whether for example ` java.util.Map` is supported. Can you refer to documentations of related java code?

**Comment by Typografikon** [comment]
I found this http://www.brightspot.com/docs/3.0/content-modeling/adding-field-types#object-fields This answers what I was asking.

**Comment by Ryan-Anderson** [comment]
Glad you found it. I'll go ahead and close this issue. Thanks

**Comment by Typografikon** [comment]
Yes, but documentation should be improved anyway! At least http://www.dariframework.org/models.html should refer to http://www.brightspot.com/docs/3.0/content-modeling/adding-field-types#object-fields 

List of supported interfaces is also missing because Object Fields article describes only annotations but not interfaces. 

Developers should be really directed in this way.  Maybe there can be also section „Commont errors and solitions“ and in this section can be „Can't use interface“ more explained.
