### ISSUE TITLE
H2 database no longer supported?

### ISSUE THREAD

**Issue by Typografikon** [perfectsense/brightspot-cms#287]
I found in [brightspot 2.4 installation tutorial](http://www.brightspot.com/docs/2.4/get-started/installation) and also in [current dari tutorial](http://www.dariframework.org/documentation.html#tutorial) that Brightspot cms / Dari  supports H2 database. In [github resources](https://github.com/perfectsense/dari/tree/master/db/src/main/resources) there is sql for h2, but was not updated for 2 years. The [database backends article](http://www.dariframework.org/database-backends.html) claims that MySQL, PostgreSQL, Oracle, Solr and MongoDB databases are supported. Looking in `com.psddev.dari.db.SqlVendor` I see H2, MySQL, Oracle and PostgreSQL databases as supported.

Is h2 database still supported and which databases are currently supported and tested? 

Thanks for response.

**Comment by Typografikon** [comment]
Looks like H2 works fine for base types but it looks like there is no support for Location type:

>    java.lang.UnsupportedOperationException: Location support is not implemented.

**Comment by rhino88** [comment]
Hi Typografikon,

We've recently added a new [H2 implementation](https://github.com/perfectsense/dari/blob/release/3.2/h2/src/main/java/com/psddev/dari/h2/H2Database.java) in Dari, complete with unit tests.

Feel free to test it, and let us know if you encounter any issues.
