### ISSUE TITLE
QUESTION: Overriding default value for a String property on a Content object

### ISSUE THREAD

**Issue by tankchintan** [perfectsense/brightspot-cms#292]
I have a class Offer that extends Content. This has a property "meta" and I set a default value for this like so,
```
public class Offer extends Content {
  
     private String meta = "some default value";
}
```
Now the problem is, if in the CMS I empty out the value for meta and publish it, it automatically takes the default value "some default value" and uses it! Instead of just setting an empty string or a null as its value in database.

Is this expected? Any way to get around it?

**Comment by Typografikon** [comment]
It should work as you descibe - when delete content it should simply save empty value. Are you sure you look at proper entity? When you search by meta you probably should add [@Indexed](http://www.brightspot.com/docs/3.0/annotations-guide/reference-guide#p-marker60) annotation to field to be able to find your entity instance. This is maybe your sticking point... I tested this with this simple class:

```java
import com.psddev.cms.db.Content;
import com.psddev.cms.db.ToolUi.Note;
import com.psddev.cms.db.ToolUi.Tab;
import com.psddev.dari.db.Recordable.DisplayName;

@DisplayName("Test")
@Note("testing entity")
public class TestContent extends Content {
	
	@Indexed
	@Tab("MyTab")
	private String title = "xxx";
}
```

With best regards,
O.

**Comment by tankchintan** [comment]
I have not added `@Indexed` annotation because I dont need annotation for it. I did not actually search for `meta`. I just got the whole object & checked all it's properties.

I did land on a solution as suggested by @kphenix offline.

I used `ToolUi.Placeholder` annotation as described [here](http://www.brightspot.com/docs/3.0/annotations-guide/ui-control).

```
    @ToolUi.Placeholder(value = "Test Entity.", editable = true)
    private String meta;
```

**Comment by kphenix** [comment]
Glad it worked @tankchintan

**Comment by Typografikon** [comment]
I am just curious that you are not able to save empty string. I think this is not related to field initialization. I suggest to check log messages when error occurs again and test it also with clean build, latest snapshot version and empty database.  There can be some validation problem or problem with object persisting.

**Comment by tankchintan** [comment]
@Typografikon there are no error messages spouted when I publish the object. I have indeed tested it with fresh build & latest snapshot. Can't do empty database though!
