### ISSUE TITLE
Question: Is there a way to customize the rendering of search results in the default search?

### ISSUE THREAD

**Issue by danbrown1113** [perfectsense/brightspot-cms#317]
If we want to make a custom search tool, we can customize the rendering of search results by extending `SearchResultRenderer`.  However, I have not found any way to modify the `SearchResultRenderer` used by the default search.  Is there any way to do this?

More detail about the specific use case we have in mind: for certain object types we use a different database implementation.  This database implementation makes a call to an external API with the search parameters.  The default `SearchResultRenderer` renders a link to each resulting object, but it only includes three query string parameters: the `typeId` of the object, the UUID of the object, and the search parameters.  However, the external API uses its own id scheme, not UUIDs, so we would like to include an additional `externalId` parameter in the link, but to do that we would need to modify the behavior of `SearchResultRenderer`.  Is there any way for us to do this?

**Comment by Ryan-Anderson** [comment]
To implement this, you would want to create your own implementation of [AbstractSearchResultView](https://github.com/perfectsense/brightspot-cms/blob/master/db/src/main/java/com/psddev/cms/tool/search/AbstractSearchResultView.java).

For an example implementation, take a look at [ListSearchResultView](https://github.com/perfectsense/brightspot-cms/blob/master/db/src/main/java/com/psddev/cms/tool/search/ListSearchResultView.java).

That should cover your use case, let us know if you have any additional questions!

**Comment by danbrown1113** [comment]
Thanks, that led me to https://github.com/perfectsense/brightspot-cms/blob/master/db/src/main/java/com/psddev/cms/tool/search/GridSearchResultView.java which I found even more helpful.
