### ISSUE TITLE
Unexpected error while saving Location with PostgreSQL 9.4.4 as backend

### ISSUE THREAD

**Issue by Typografikon** [perfectsense/brightspot-cms#322]
Hi,  

there is an unexpected error while saving Location - brightspot-cms  v3.1.4461-c7651a, PostgreSQL 9.4.4, jdbc driver 9.4-1202-jdbc42, Tomcat 8.0.24, java 1.8.0_51. Occurs also when empty database is initialized. See stacktrace below. There is no problem when Mysql is used.

O.

> Zář 30, 2015 11:55:40 ODP. com.psddev.dari.db.SqlDatabase$Static logUpdateException
> SEVERE: Batch update failed with query 'INSERT INTO recorduuid3 (id,typeid,symbolid,value) VALUES (?, ?, ?, ?)' with values (21befeed-f48f-313f-8577-7e67a616fc6e, 00000150-203f-da31-a1fb-bbbfb095001e, 43, 1dd01f39-ddfe-4b2c-95db-e0ca9e4eb03f)
> Zář 30, 2015 11:55:40 ODP. com.psddev.dari.db.SqlDatabase$Static logBatchUpdateException
> SEVERE: 
> org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "recorduuid3_pkey"
>   Detail: Key (symbolid, value, typeid, id)=(45, 00000150-2040-da31-a1fb-bbc535b80000, 00000150-203f-da31-a1fb-bbbfb095001e, 21befeed-f48f-313f-8577-7e67a616fc6e) already exists.
>     at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
>     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
>     at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1105)
>     at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1126)
>     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:329)
>     at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2888)
>     at org.apache.tomcat.dbcp.dbcp2.DelegatingStatement.executeBatch(DelegatingStatement.java:344)
>     at org.apache.tomcat.dbcp.dbcp2.DelegatingStatement.executeBatch(DelegatingStatement.java:344)
>     at com.psddev.dari.db.SqlDatabase$Static.executeBatchUpdate(SqlDatabase.java:3196)
>     at com.psddev.dari.db.SqlIndex$Static.insertByStates(SqlIndex.java:983)
>     at com.psddev.dari.db.SqlIndex$Static.insertByStates(SqlIndex.java:899)
>     at com.psddev.dari.db.SqlDatabase.doSaves(SqlDatabase.java:2508)
>     at com.psddev.dari.db.SqlDatabase.doSaves(SqlDatabase.java:76)
>     at com.psddev.dari.db.AbstractDatabase.doWrites(AbstractDatabase.java:1265)
>     at com.psddev.dari.db.AbstractDatabase.write(AbstractDatabase.java:980)
>     at com.psddev.dari.db.AbstractDatabase.doCommitWrites(AbstractDatabase.java:715)
>     at com.psddev.dari.db.AbstractDatabase.commitWrites(AbstractDatabase.java:695)
>     at com.psddev.dari.db.AggregateDatabase$$Lambda$10/1248287870.test(Unknown Source)
>     at com.psddev.dari.db.AggregateDatabase.batch(AggregateDatabase.java:367)
>     at com.psddev.dari.db.AggregateDatabase.commitWrites(AggregateDatabase.java:398)
>     at com.psddev.dari.db.State.saveImmediately(State.java:2209)
>     at com.psddev.dari.db.Record.saveImmediately(Record.java:397)
>     at com.psddev.cms.tool.page.content.EditFieldUpdate.save(EditFieldUpdate.java:58)
>     at com.psddev.cms.tool.page.content.EditFieldUpdateAction.execute(EditFieldUpdateAction.java:38)
>     at com.psddev.cms.rtc.RtcHandler.onRequest(RtcHandler.java:140)
>     at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:197)
>     at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:108)
>     at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:66)
>     at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2262)
>     at com.psddev.cms.rtc.RtcFilter.doRequest(RtcFilter.java:131)
>     at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:408)
>     at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:570)
>     at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:280)
>     at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:563)
>     at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:280)
>     at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:563)
>     at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:280)
>     at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:563)
>     at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:280)
>     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
>     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
>     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
>     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
>     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
>     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
>     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
>     at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
>     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
>     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
>     at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
>     at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
>     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1527)
>     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1484)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
>     at java.lang.Thread.run(Thread.java:745)

**Comment by rhino88** [comment]
Moving this issue to Dari repo https://github.com/perfectsense/dari/issues/258
