### ISSUE TITLE
RichText - link to StorageItem

### ISSUE THREAD

**Issue by Typografikon** [perfectsense/brightspot-cms#342]
Hi, 

I have class with field StorageItem file:
```java
public class Download extends Content {
	@Indexed
	@Required
	protected StorageItem file;
	// ...
}
```

and I want to be able to link these download file from RichText editor in cms administration. When I select text in editor than click on link icon and choose to select from content, than I see only items implementing Directory.Item interface. It is ok for normal articles, but what about StorageItems? I consider that there is some way how to use file.getPublicUrl() as link url (and this url can be on different host).

I quess I dont need enchancements for this task so I dont need @Referenceable, @PreviewField etc.? Or?

**Comment by Ryan-Anderson** [comment]
Hi Ondrej,

The search that displays the `Content` available for linking is restricted to any `Content` that has a `path` (which includes `Directory.Item`). The recommendation here would be to either implement `Directory.Item` or create an enhancement via `@ToolUi.Referenceable` and `@Renderer.Path`.

**Comment by Typografikon** [comment]
Thanks for response. You suggested two possible methods, which one is better to add simple plain download links to StorageItems in my WYSIWYG text articles? I have no idea how to implement Directory.Item in my Download class, do you have some example code?

**Comment by Ryan-Anderson** [comment]
Rich Text Enhancements are currently limited to block level only. We are currently working on "Inline" enhancements, which would be perfect for this use case. 

For now, here is a simple implementation to get you the desired result:

```

public class Download extends Content implements Directory.Item {

    @Indexed
    @Required
    private StorageItem file;

    public StorageItem getFile() {
        return file;
    }

    public void setFile(StorageItem file) {
        this.file = file;
    }

    @Override
    public String createPermalink(Site site) {
        return "/" + DownloadFilter.URL_PREFIX + "/" + this.getId();
    }
}
```

```
import com.psddev.dari.util.AbstractFilter;
import com.psddev.dari.util.JspUtils;

public class DownloadFilter extends AbstractFilter implements AbstractFilter.Auto {

    public static final String URL_PREFIX = "/_download/";

    @Override
    protected void doRequest(HttpServletRequest request, HttpServletResponse response, FilterChain chain) throws Exception {
        if (request.getServletPath().startsWith(URL_PREFIX)) {
            Object object = Directory.Static.findByPath(PageFilter.Static.getSite(request), request.getServletPath());
            if (object instanceof Download) {
                Download download = (Download) object;
                JspUtils.redirect(request, response, download.getFile().getPublicUrl());
            }
        }

        chain.doFilter(request, response);
    }

    @Override
    public void updateDependencies(Class<? extends AbstractFilter> filterClass, List<Class<? extends Filter>> dependencies) {
        if (PageFilter.class.isAssignableFrom(filterClass)) {
            dependencies.add(getClass());
        }
    }
}
```

the DownloadFilter will run before `PageFilter` (by way of the `AbstractFilter.Auto` implementation) and 
redirect to the resource in the appropriate storage.

Hopefully that provides the functionality you require.

**Comment by Typografikon** [comment]
Many thanks, it looks like it matches my needs. I test in real project let you know.

**Comment by rhino88** [comment]
I'll go ahead and close this issue, but let me know if you have additional questions here.
