### ISSUE TITLE
How to delete permanently all archived records?

### ISSUE THREAD

**Issue by Typografikon** [perfectsense/brightspot-cms#343]
Hi to all, 

I have simple question: How to delete permanently all archived records? Cannot get query to select archived records.

Thanks,
O.

**Comment by Ryan-Anderson** [comment]
To Query for all archived `Content`, you will need to add a predicate for the `trash` field of `Content`. You will notice that the field has an `@InternalName` annotation which maps the field to `cms.content.trashed` (https://github.com/perfectsense/brightspot-cms/blob/master/db/src/main/java/com/psddev/cms/db/Content.java#L94).

Here is an example Query:

```
Query.from(Content.class).where("cms.content.trashed = true").selectAll();
```

**Comment by Typografikon** [comment]
Thanks for response and clarifications, I didn know @InternalName annotation before. It works great.
