### ISSUE TITLE
resolveInvisible() with multiple levels of hidden content.

### ISSUE THREAD

**Issue by yuriydr** [perfectsense/brightspot-cms#346]
Hi, we have a similar issue to https://github.com/perfectsense/brightspot-cms/issues/183, but we can possibly have multiple levels of "pending" content. We want to use History.getObject() with resolveInvisible(), but we have not been successful in getting more than one level of hidden objects to be resolved. If a hidden object has another hidden object in it, we can't get it show up, it's always null.

**Comment by rhino88** [comment]
Hi @yuriydr, would it be possible for you to provide me with a code sample for what you are trying to accomplish?

**Comment by yuriydr** [comment]
I will try to explain it more. Basically the situation is a History object (the object retrieved by History.getObject()) that contains a hidden item, and that hidden item also contains another hidden item.

Initially, we thought that we couldn't even get the first hidden item to show up (and implemented our own method to retrieve an item from history), but then we learned that setting resolveInvisible on the item returned by History.getObject() works, if you do it before getting any of its members.

However, my question is regarding the fact that the resolveInvisible flag isn't carried to the hidden "subobjects", and if they have hidden objects within them, you have to do additional queries with the resolveInvisible flag at each "level" that you want to find hidden content for.

But finally, we also learned that even a change to this behavior won't work in our case, because we treat initial drafts and drafts of published items equally in the situation where this is needed, and for drafts of published items, you always have to run separate queries anyway.

**Comment by rhino88** [comment]
Hi Yuri, 

You can accomplish this by temporarily overriding the default database:

```
try {
    ForwardingDatabase db = new ForwardingDatabase() {
        @Override
        protected <T> Query<T> filterQuery(Query<T> query) {
            return query.clone().master().resolveInvisible().option(Database.DISABLE_FUNNEL_CACHE_QUERY_OPTION, true);
        }
    };


    db.setDelegate(Database.Static.getDefault());
    Database.Static.overrideDefault(db);

    // perform your query normally here...

} finally {
    Database.Static.restoreDefault();
}
```

Hope that helps!
