### ISSUE TITLE
Unique index or primary key violation with h2 database

### ISSUE THREAD

**Issue by Typografikon** [perfectsense/brightspot-cms#494]
Hi to all, 

I got _Unique index or primary key violation_ thrown from database, but no error is seen in cms administration. It looks like this occurs when I save items attached in „Work Streams“. I use dari version 3.2.2105-69b775 and cms version 3.2.5106-141334 in combination with h2 database 1.4.191. Exception log and database scheme is attached:
- [database_schema.txt](https://github.com/perfectsense/brightspot-cms/files/121983/database_schema.txt)
- [unique_exception.txt](https://github.com/perfectsense/brightspot-cms/files/121984/unique_exception.txt)

Any idea what is wrong?

With best regards
Ondrej Nemecek

**Comment by Typografikon** [comment]
Any idea to this issue? I got no error when saving all objects in simple Task:

```java
List<? extends Record> records = Query.from(typeClass).selectAll();
// ...loop each record and save...
record.save();
```

It looks like issue is cms-ui related, not my models-related.

With best regards,
Ondrej.

**Comment by rhino88** [comment]
Hi Typografikon,

We've recently added a new [H2 implementation](https://github.com/perfectsense/dari/blob/release/3.2/h2/src/main/java/com/psddev/dari/h2/H2Database.java) in Dari, complete with unit tests.

Feel free to test it, and let us know if you encounter any issues.
