### ISSUE TITLE
Broken link to Postgres & MySQL DDL in database-backends doc

### ISSUE THREAD

**Issue by worldofchris** [perfectsense/brightspot-cms#53]
On this page:

https://github.com/perfectsense/brightspot-cms/blob/master/docs/documentation/database-backends.md

The link to:

https://github.com/perfectsense/dari/blob/master/etc/postgres/schema-11.sql

404s.

The MySQL one does the same:

https://github.com/perfectsense/dari/blob/master/etc/mysql/schema-11.sql

The Oracle ones work.

**Comment by kphenix** [comment]
Thanks. The location of the files and documentation has changed recently:

Documentation: http://www.brightspot.com/docs/2.4/advanced-configuration/databases
Resource files: https://github.com/perfectsense/dari/tree/master/db/src/main/resources
