### ISSUE TITLE
Problem with solrconfig.xml for development installation

### ISSUE THREAD

**Issue by MichelinMan** [perfectsense/brightspot-cms#55]
I am following the documentation for the development installation of brightspot,from here
http://www.brightspot.com/docs/2.4/get-started/installation#development-installation

I have had problems with the brightspot solrconfig.xml file.

A request to http://localhost:8080/solr/admin/ returns an HTTP Status 404 - missing core name in path.
At the same time the tomcat logs have a stack trace complaining about this value
<luceneMatchVersion>LUCENE_40</luceneMatchVersion>

SEVERE: org.apache.solr.common.SolrException: Invalid luceneMatchVersion 'LUCENE_40', valid values are: [LUCENE_20, LUCENE_21, LUCENE_22, LUCENE_23, LUCENE_24, LU
CENE_29, LUCENE_30, LUCENE_31, LUCENE_32, LUCENE_33, LUCENE_34, LUCENE_35, LUCENE_36, LUCENE_CURRENT] or a string in format 'V.V'

I replaced the value with 36 and then I got the same 404 error and this time another stack trace about a ClassNotFoundException

SEVERE: org.apache.solr.common.SolrException: Error loading class 'solr.RealTimeGetHandler'
...
Caused by: java.lang.ClassNotFoundException: solr.RealTimeGetHandler

When I comment out the xml that loads the class in the solrconfig.xml, and load tomcat I finally get the  Solr service running.

Maybe this solrconfig.xml file is Solr4 specific, and 3.6 does not have that class, and it doesn't support values above 36 in luceneMatchVersion?

Many thanks,
Ioannis

**Comment by kphenix** [comment]
Ioannis,

This was an issue with the wrong branch being used for the solr config file. The docs are now updated. 2.4 branch has the correct configs.

**Comment by MichelinMan** [comment]
thank you,
Ioannis
