### ISSUE TITLE
Getting Content attributes in Renderer servlet

### ISSUE THREAD

**Issue by worldofchris** [perfectsense/brightspot-cms#56]
Hi,

We are looking at using alternatives to jsp to present the Content in our BrightSpot application.

We have created a new Servlet, mapped it's url pattern to match the @Renderer.Path for the Content and are seeing it run when the url for the content is requested in the browser from BrightSpot.

All good.

What is not clear is how in the Servlet you access the attributes of the Content for the Renderer to present.

Is anyone able to advise?

Looking at the [Freemarker Example](https://github.com/danslaughter2/freemarker-demo) it looks like the [ClassFinder](https://github.com/danslaughter2/freemarker-demo/blob/master/src/main/java/com/psddev/freemarker/ftl/FreemarkerServlet.java#L3) class is involved.

Is there any documentation or examples of how to discover the context in which a Renderer is being invoked, i.e. what Content is the Renderer being asked to Render?

I'll keep digging through the Freemarker demo but if anyone is able to help in the meantime that would be greatly appreciated.

Thanks

**Comment by Ryan-Anderson** [comment]
I think what you are looking for can be found in the PageFilter:

https://github.com/perfectsense/brightspot-cms/blob/master/db/src/main/java/com/psddev/cms/db/PageFilter.java#L1504

or

https://github.com/perfectsense/brightspot-cms/blob/master/db/src/main/java/com/psddev/cms/db/PageFilter.java#L1573

Take a look at how the mainContent and content attributes are set on the request, and you can access them in your servlet from there.

Also, just out of curiosity, which jsp alternative are you implementing?

**Comment by worldofchris** [comment]
Hey @Ryan-Anderson many thanks for that.

A great help.

Got it working here:

https://github.com/wearefriday/brightspot-handlebars

Using (handlebars.java)[https://github.com/jknack/handlebars.java]

Thanks for your help.  We will be continuing to work on the integration and will add to the repo as we go.
