### ISSUE TITLE
No default database! (check [dari/defaultDatabase] setting) (com.psddev.dari.util.SettingsException)

### ISSUE THREAD

**Issue by MichelinMan** [perfectsense/brightspot-cms#57]
Hi,

I am having a problem bringing up an instance of brightspot after seemingly having installed and configured an instance or a ubuntu 14.04 VM according to the documentation.

When I point to http://localhost:8080/cms I get the error above, "No default database!"

This is despite the fact that the database is correctly configured in context.xml.

I copy past the unusable playbook that I use to set-up and configure the VM:

---
- hosts: all
  sudo: true
  tasks:
    - name: update apt cache
      apt: update_cache=yes

    - name: install openJDK 7
      apt: name=openjdk-7-jdk state=present

    - name: install Maven 3
      apt: name=maven state=present

###Tomcat 7###
    - name: install Tomcat 7
      apt: name={{ item }} state=present
      with_items:
        - tomcat7
        - tomcat7-admin

#TODO# specify owner:group in all template module calls
    - name: configure Tomcat 7 admin user
      template: src=templates/tomcat-users.xml.j2 dest=/etc/tomcat7/tomcat-users.xml

    - name: create brightspot media directory
      file: path=/var/lib/tomcat7/webapps/media-files owner=tomcat7 group=tomcat7 state=directory

#TODO# log ticket with brightspot about the context typo
    - name: replace context.xml
      template: src=templates/context.xml.j2 dest=/var/lib/tomcat7/conf/context.xml

    - name: reload Tomcat 7
      service: name=tomcat7 state=restarted
###

###Solr###
    - name: download Solr 3.6.2
      get_url:
        url=http://archive.apache.org/dist/lucene/solr/3.6.2/apache-solr-3.6.2.tgz
        dest=/home/vagrant/apache-solr-3.6.2.tgz

    - name: expand Solr 3.6.2
      command:
        tar -xf apache-solr-3.6.2.tgz
        creates=/home/vagrant/apache-solr-3.6.2/README.txt

    - name: place the solr.war file in the Tomcat webapps directory
      command:
        cp -r /home/vagrant/apache-solr-3.6.2/dist/apache-solr-3.6.2.war /var/lib/tomcat7/webapps/solr.war
        creates=/var/lib/tomcat7/webapps/solr.war

    - name: copy Solr home into the Tomcat root directory
      command:
        cp -r /home/vagrant/apache-solr-3.6.2/example/solr /var/lib/tomcat7
        creates=/var/lib/tomcat7/solr/README.txt

    - name: replace the solrconfig.xml with project-specific version
      template: src=templates/solrconfig.xml.j2 dest=/var/lib/tomcat7/solr/conf/solrconfig.xml

    - name: replace the schema.xml with project-specific version
      template: src=templates/schema.xml.j2 dest=/var/lib/tomcat7/solr/conf/schema.xml

    - name: set Solr home owner:group
      file: path=/var/lib/tomcat7/solr owner=tomcat7 group=tomcat7 recurse=yes

    - name: reload Tomcat 7
      service: name=tomcat7 state=restarted
###

###MySQL###
    - name: install MySQL 5.5
      apt: name=mysql-server-5.5 state=present

    - name: install python-mysqldb, required by ansible
      apt: name=python-mysqldb state=present

#TODO# put db name, user name and pass in a variable, here and in the context.xml.j2 template
    - name: create CMS DB
      mysql_db: name=brightspot_db state=present

    - name: create CMS DB user/password with all DB privileges and 'WITH GRANT OPTION'
      mysql_user:
        name=brightspot_user
        password=12345678
        priv=*.*:ALL,GRANT
        state=present

    - name: download mysql-connector
      get_url:
        url=http://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.34.tar.gz
        dest=/home/vagrant/mysql-connector-java-5.1.34.tar.gz

    - name: expand mysql-connector
      command:
        tar -xf mysql-connector-java-5.1.34.tar.gz
        creates=/home/vagrant/mysql-connector-java-5.1.34

    - name: place the mysql-connector jar into the tomcat lib directory
      command:
        cp -r /home/vagrant/mysql-connector-java-5.1.34/mysql-connector-java-5.1.34-bin.jar /usr/share/tomcat7/lib/
        creates=/usr/share/tomcat7/lib/mysql-connector-java-5.1.34-bin.jar
###

### Generate a maven archetype, build and then deploy to recently configured tomcat ###
    - name: generate a maven archetype
      command: mvn archetype:generate -B -DarchetypeRepository=http://public.psddev.com/maven -DarchetypeGroupId=com.psddev -DarchetypeArtifactId=cms-app-archetype -DarchetypeVersion=2.4-SNAPSHOT -DgroupId=com.project -DartifactId=yourProject
      args:
        creates: /home/vagrant/yourProject/pom.xml

    - name: build brightspot
      command: mvn clean install
      args:
        chdir: /home/vagrant/yourProject/

    - name: undeploy the existing ROOT.war file
      command: rm -rf /var/lib/tomcat7/webapps/ROOT.war

    - name: undeploy the existing ROOT directory
      command: rm -rf /var/lib/tomcat7/webapps/ROOT

    - name: deploy war file to tomcat webapps directory
      command:
        cp -r /home/vagrant/yourProject/target/yourProject-1.0.0-SNAPSHOT.war /var/lib/tomcat7/webapps/ROOT.war

    - name: reload Tomcat 7
      service: name=tomcat7 state=restarted

#TODO# refactor all the command with args:

I also copy-paste the unusable  context.xml template, so you can see that the MySQL configuration in the playbook and context.xml match

<?xml version='1.0' encoding='utf-8'?>
<Context allowLinking="true" crossContext="true" cachingallowed="false">
<watchedresource>WEB-INF/web.xml</watchedresource>

<environment name="cms/tool/isAutoCreateUser" override="true" type="java.lang.Boolean" value="true" />

<environment name="dari/defaultDatabase" type="java.lang.String" value="brightspot_db" override="false" />
<environment name="dari/database/brightspot_db/class" override="false" type="java.lang.String" value="com.psddev.dari.db.AggregateDatabase" />
<environment name="dari/database/brightspot_db/defaultDelegate" override="false" type="java.lang.String" value="sql" />
<environment name="dari/database/brightspot_db/delegate/sql/class" override="false" type="java.lang.String" value="com.psddev.dari.db.SqlDatabase" />

<resource name="dari/database/brightspot_db/delegate/sql/dataSource" auth="Container" driverclassname="com.mysql.jdbc.Driver" logabandoned="true" maxactive="100" maxidle="30" maxwait="10000" type="javax.sql.DataSource" removeabandoned="true" removeabandonedtimeout="60" username="brightspot_user" password="12345678" url="jdbc:mysql://localhost:3306/brightspot_db" testonborrow="true" validationquery="SELECT 1" />

<environment name="solr/home" override="false" type="java.lang.String" value="/var/lib/tomcat7/solr" />
<environment name="dari/database/brightspot_db/delegate/solr/groups" override="false" type="java.lang.String" value="-* +cms.content.searchable" />
<environment name="dari/database/brightspot_db/delegate/solr/class" override="false" type="java.lang.String" value="com.psddev.dari.db.SolrDatabase" />
<environment name="dari/database/brightspot_db/delegate/solr/serverUrl" override="false" type="java.lang.String" value="http://localhost:8080/solr" />

<environment name="dari/defaultStorage" type="java.lang.String" value="local" override="false" />
<environment name="dari/storage/local/class" override="false" type="java.lang.String" value="com.psddev.dari.util.LocalStorageItem" />
<environment name="dari/storage/local/rootPath" override="false" type="java.lang.String" value="/var/lib/tomcat7/webapps/media-files" />
<environment name="dari/storage/local/baseUrl" override="false" type="java.lang.String" value="http://localhost:8080/media-files" />

</context>

Can you reproduce this? Or perhaps spot a configuration error in the file paths for example? Everything seems ok to me.

Many thanks,
Ioannis

**Comment by MichelinMan** [comment]
I am using MySQL 5.5, i am aware you specified 5.6. Could this be the issue?

Many thanks,
Ioannis

**Comment by kphenix** [comment]
Ioannis,

Not sure which context.xml you are using - can you try this one (This doesn't include the defaultStorage settings)

https://gist.githubusercontent.com/kphenix/54ca0f473ef7e034811a/raw/c5c0bffb1fb18c85ea960064435d49a4028763e6/default-context-2.4.xml

**Comment by MichelinMan** [comment]
Thank you Karl,
I was using the context.xml that was linked to from the installation notes.
This new one works, I have a working instance of brightspot running.
Very happy.

Thanks again,
Ioannis
