### ISSUE TITLE
JSP tags into raw content were ignored

### ISSUE THREAD

**Issue by gestern** [perfectsense/brightspot-cms#58]
How do I get "dynamic content" which would be placed as database stuff? I'm tried to create "_Raw HTML_" with "/test" static url, but when I accessed with the url all of jsp tags rendered as (for example):

```html
<%@include file="/WEB-INF/common/taglibs.jsp" %>
```
How to avoid printing `<%%>` ? Is it possible?

**Comment by Ryan-Anderson** [comment]
Jsp tags are not valid html tags. When you create "Raw Html" Content, you will only be able to use static html.

To render dynamic html you will need to create your page or template in a JSP.

For your convenience, here is a link to the documentation that how to do this: http://www.brightspotcms.com/docs/2.4/templating/creating-pages-templates

**Comment by gestern** [comment]
Thanks, but might better if the user will have a chance to make "rendering content" through cms to avoid creating any of jsp files without cms. For instance, via checking a check box "Rendering context by JSP processor" into cms. What you thinking about?

**Comment by Ryan-Anderson** [comment]
The Brightspot platform allows developers to quickly create content objects and templates as well as modules for editors to publish. Editors are not typically the users writing any code, but rather are publishing the templates and modules the developers have built in the Java application.

A Content type like you are requesting would not be difficult to create, but it does not come "out of the box" with Brightspot, as it is not a commonly requested feature.
