### ISSUE TITLE
Broken Installation

### ISSUE THREAD

**Issue by wiverson** [perfectsense/brightspot-cms#59]
Installing on Mac OS X (10.10.2) with the current JDK 1.8 (Java version: 1.8.0_25, vendor: Oracle Corporation) and Maven 3.2.5 leads to broken install.

Navigating to localhost:8080/cms/ leads to this error message:

```
Can't render /cms/index.jsp!

No default database! (check [dari/defaultDatabase] setting) (com.psddev.dari.util.SettingsException)
com.psddev.dari.util.Settings.checkValue(Settings.java:303)
com.psddev.dari.util.Settings.getOrError(Settings.java:351)
com.psddev.dari.db.Database$Static.getDefaultOriginal(Database.java:218)
```

I also noticed that there is a SNAPSHOT dependency, http://public.psddev.com/maven/com/psddev/cms-db/2.4-SNAPSHOT, which is Not Good(tm) for a variety of reasons.

Checking the docs briefly, the /src/main/resources directory is empty, but it looks like there should be a configuration file there?

Clicking a bit around in issues, it looks like down rev to JDK 1.7 is the only answer...?  Java 1.8 came out in March 2014, so I'm a bit nervous that there is no 1.8 support yet, almost a year later...?

**Comment by kphenix** [comment]
Will,

Brightspot supports java 1.8. The issue you are seeing is likely related to an issue with your context.xml 

Recently we saw the same issue - https://github.com/perfectsense/brightspot-cms/issues/57 and it was resolved with the updated context.xml

https://gist.githubusercontent.com/kphenix/54ca0f473ef7e034811a/raw/29acee59ecc2e431cd1bfc46a4bcb049c52e1e8d/default-context-2.4.xml

Let me know if that works.

**Comment by wiverson** [comment]
I looked at the gist, looks like that expects to point to a local MySQL install.  Do you have one that works with out-of-the-box H2?  Tried popping an in-memory H2 JDBC URL in to see if that would work, didn't seem to pick anything up.

**Comment by wiverson** [comment]
As a tip, add a Jenkins job on a CI server somewhere that checks out the archetype, includes a basic verification integration test case (you already have Cargo automation, the hard part) and have it run daily as a safety check.

Let me know if I can help you guys with that...  :)

**Comment by kphenix** [comment]
Thanks Will. Did you get setup ok? The Cargo install runs on a H2 in-memory DB out-of-the-box (That's the quick installation guide here: http://brightspot.com/docs/2.4/get-started/installation )

**Comment by wiverson** [comment]
Nope, the out-of-box w/H2 is what's not working.  :(

Vanilla Mac install (version #s above).

**Comment by kphenix** [comment]
Will,

Got it. Apologies - I wasn't aware from your first issue that it was the Cargo quick start install that you were using. That does require Java 1.7. We are working on a replacement for the quick start.

The development installation supports Java 1.8

**Comment by wiverson** [comment]
Any idea why the H2 install blows up on 1.7?

**Comment by lteague** [comment]
8ee11de should address this issue.

**Comment by wiverson** [comment]
Patch works.  Logged in now.  Getting an error in the admin page, I'll open a new issue for that.
