### ISSUE TITLE
Issues while migrating HTML formatted data to ReferentialText.

### ISSUE THREAD

**Issue by prasheetha** [perfectsense/brightspot-cms#615]
Hi Team,

I have few articles in relation database system, I need to migrate those into Brigthtspot CMS. The format of the data look like below.

ArticleName: ABC
ArticleBody:
<div style="text-align: center;">
 	<div style="text-align: center;">
 		<p>
 			<span style="color: rgb(255, 0, 51);"><u><em style="color: rgb(255, 0, 51);"><span style="font-size: 21.81px;"><b>BODY CONTENT</b></span></em></u></span></p>
 		<p>
</div>
</div>
PublishDate: 03/10/2016.

Issue: When I migrate ArticleBody into ReferntialText, it is striping(removing) all the HTML formats such as style="text-align: center;" and style="font-size: 21.81px;". hence i'm missing all the formats in CMS.

Could you please assists how can I migrate data like this into ReferentialText?

Code Snippet:
ReferentialText txt = new ReferentialText();
txt.addHtml(informationArticles.getString("ArticleBody"));

Thanks in advance.

Regards, 
Prasheetha.

**Comment by hyoolim** [comment]
We've changed our rich text implementation to use CodeMirror, which retains these types of custom HTML formatting, and it's available from v3.1 and up.
