### ISSUE TITLE
BrightSpot CMS: Tool UI  FAILURE

### ISSUE THREAD

**Issue by sriranjinidey** [perfectsense/brightspot-cms#623]
Please help. 3.2 does not build. 

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.26:grunt (grunt) on project cms-tool-ui: Failed to run task: 'grunt --bsp-maven-build-finalName=cms-tool-ui-3.2-SNAPSHOT --no-color' failed. (error code 3) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.26:grunt (grunt) on project cms-tool-ui: Failed to run task

**Comment by nevermind89x** [comment]
Wondering what was the solution?

**Comment by revgen** [comment]
I had this problem too.
To fix it: I created an empty main.js file inside the src/main/webapp and it helped me.
Details: https://github.com/perfectsense/brightspot-cms/issues/1039
