### ISSUE TITLE
Resource cannot be found when using @ToolUi.InputSearcherPath annotation

### ISSUE THREAD

**Issue by KodakAlarisUser** [perfectsense/brightspot-cms#64]
Version: 2.4-SNAPSHOT
Description: I would like to use a custom search widget to sort not only by object type, but also by the value of a field on that object. When I annotate the field with @ToolUi.InputSearcherPath("/somePath/searchWidget.jsp"), the resource cannot be found (error 404). To verify that the file can be seen in other contexts, I replaced the annotation with @ToolUi.InputProcessorPath("/somePath/searchWidget.jsp"), and the resource was found successfully.

**Comment by Ryan-Anderson** [comment]
Hi Christina, 

I have a temporary workaround you can use:

The annotation currently looks for the searcher jsp in the `/cms/content` directory. If you create these directories in your project (under `webapp`), and move your jsp to the `content` directory, the custom search widget will function as expected.

Let us know if this workaround works for you.

**Comment by christinaBell** [comment]
Yes, the workaround works just fine until the issue has been resolved.  Thanks!
