### ISSUE TITLE
How do you get a Content class to appear in the Bulk Upload list?

### ISSUE THREAD

**Issue by worldofchris** [perfectsense/brightspot-cms#66]
I would like to use the Bulk Upload list to upload a number of instances of a specific Content Class from a CSV file.

I have added the @ToolUi.BulkUpload decorator to the fields that I want to be populated.

The problem I have is that the Content Class itself is not appearing in the drop down list of content classes to select in the UI.

A subset of the Content Classes I have created _do_ appear but I can't see what the common denominator is for them.

What do you need to do, or what determines, whether a given content class appears in the drop down list of content classes that can be uploaded using the bulk uploader?

Thanks

**Comment by hyoolim** [comment]
The bulk upload dashboard widget accepts files, so only the content types that contain one or more `StorageItem` fields show there. If you want some custom functionality, you'd probably want to create your own dashboard widget.

**Comment by worldofchris** [comment]
Got it.  Thanks.
