### ISSUE TITLE
User input and validation examples

### ISSUE THREAD

**Issue by asktomsk** [perfectsense/brightspot-cms#7]
I can't find anything about user input controls and validation in documentation.
For example I created Article and want to allow user write comments.
How to implement it?

I see things like `cms:input` with not clear attributes like `object` and `writer`. How to use them?

Also would be good to provide example application with most of functionality covered.
Thanks.

**Comment by rhino88** [comment]
Brightspot does not currently provide out-of-the-box input validation for your user-facing site. You would need to implement your own.
