### ISSUE TITLE
Custom UI

### ISSUE THREAD

**Issue by KodakAlarisUser** [perfectsense/brightspot-cms#71]
We have a particular need that I wanted to ask if you had support for:
We have a piece of Content that contains a collection of some object.  This object itself has 1-3 fields on it based on the context in which it is being used.  We would like to dynamically display certain fields based on some condition so that the editor will only see the fields they are required to enter data in.  We could create a model for each permutation, but would like to avoid creating too many classes for special cases.
 
According to your documentation, it looks like we should be able to do this using the @InputProcessorPath annotation.  We have been able to successfully draw the required fields on the page based on some condition, but it is unclear how we should store the data to maintain state because when we put the objects in the State object, the values are not persisting after a publish.  Is there a way to link the elements drawn on the page to the data?  Should we be generating a UUID to achieve this?  I also noticed a statement on your site that you are currently working on the Custom UI documentation.  Is it still in progress or can you point me to it?

Thanks!

**Comment by kphenix** [comment]
A good start to creating custom fields is to use the Brightspot native examples such as https://github.com/perfectsense/brightspot-cms/blob/master/tool-ui/src/main/webapp/WEB-INF/field/uuid.jsp
