### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by ian-bartholomew** [perfectsense/brightspot-cms#726]
When trying to install from the 3.2 documentation, after installation, when navigating to the install url, you receive this error:

```
Can't render /cms/logIn.jsp!

Unable to compile class for JSP: 

An error occurred at line: 96 in the jsp file: /cms/logIn.jsp
Type mismatch: cannot convert from Object to boolean
93:     String siteUrl = Query.from(CmsTool.class).first().getDefaultSiteUrl();
94:     String domain = getDomain(siteUrl);
95:     String ipAddress = getIpAddress(request.getHeader("X-FORWARDED-FOR"), request.getRemoteAddr());
96:     boolean isAuthLogged = Settings.get(boolean.class, "cms/tool/isAuthenticationLogged");
97: 
98:     try {
99:
Parameters:
returnPath=/cms/index.jsp
```

**Comment by lteague** [comment]
@ian-bartholomew, which version of Tomcat are you using? There is a known bug in recent versions of Tomcat that presents itself in this way. 8.0.33, the very latest version, is known to have this issue.

Can you try downgrading to 8.0.30?

**Comment by ian-bartholomew** [comment]
I was running 8.0.33, downgrading to 8.0.30 did the trick, thank you
