### ISSUE TITLE
How to get the annotated note associated with a property of a Content object?

### ISSUE THREAD

**Issue by tankchintan** [perfectsense/brightspot-cms#77]
I want to get the TooliUi.NoteHtml value associated with the property of a subclass of Content class.
Is there a way to do this?
I know that the CMS does it (because we can see the annotated value for `ToolUi.Note` for a proeprty in the interface).

I have been trying the below. And I am pretty sure it’s wrong hence need some guidance.
```
SubscriptionPlan extends Content {

        @ToolUi.NoteHtml("THIS IS THE MESSAGE");
        private boolean isActive;       
}

//Some other piece of code
 SubscriptionPlan plan = ...;
 ObjectType type = plan.getState().getType();

 String response = type.as(ToolUi.class).getEffectiveNoteHtml(plan); 

/* The value for "response" above should be the NoteHtml associated with the "isActive" property 
which is >>> THIS IS THE MESSAGE */
```

**Comment by hyoolim** [comment]
In your example, if you want to get the note HTML markup for the `isActive` field in the `SubscriptionPlan` class, you can do:

    SubscriptionPlan plan = ...;
    String noteHtml = plan.getState().getType().getField("isActive").as(ToolUi.class).getEffectiveNoteHtml(plain);

**Comment by tankchintan** [comment]
Perfect @hyoolim exactly, what Iw as looking for!
