### ISSUE TITLE
Tab issues in Drafts in upgrade to 3.2.4

### ISSUE THREAD

**Issue by lajoiechristina** [perfectsense/brightspot-cms#848]
We recently upgraded from 3.1 to 3.2.4 and discovered a UI issue related to Drafts where tabs are not displayed in the Draft view.

Steps to reproduce:

1. Create new content for a type that contains multiple Tabs (@ToolUI.Tab()).
2. In one of the tabs, don't set any fields (i.e., leave then unset or empty).
3. In the other tabs, set some data.
4. Publish the content.
5. In **one** of the tabs where data was already set, make a change.
6. In the _Publish_ widget, select **Save Draft**
7. Once the Draft is open, notice that the only tabs displayed are for data that was changed and for data that was never set.

This is an issue that would block us from upgrading.  Is it an issue you are aware of and/or will have a fix for soon?  Thanks!

**Comment by hyoolim** [comment]
Thanks for the bug report. We were tracking this internally already, and it should be fixed when #850 is merged.
