### ISSUE TITLE
How to implement the site search functionality

### ISSUE THREAD

**Issue by DevDh** [perfectsense/brightspot-cms#87]
Hi,
I am trying to implement the Site search functionality, but found that 'com.psddev.cms.db.Search' is deprecated.

It would be really helpful if you can assist on how to implement the Site Search functionality. The current BrightSpot documentation does not talk much on the Site Search.

I would really appreciate for your inputs.

Thanks,
Dev

**Comment by kdyer** [comment]
Hello, 

You'll want to look at the `SearchQueryBuilder` object for the search functionality. If there is an added editorial component (for example, allowing editors to control various parts of the search itself) then you would want to also look at the `EditorialSearchSettings` object. Your implementation will mostly depend on the business rules for your search.

For the purpose of the example, we'll set the following business rules:
- search content types Articles, Images, and Video
- rank Article types to have more weight
- editors can control stop words, synonyms, and the number of search results returned
```
public class SiteSearch extends EditorialSearchSettings implements Singleton, Directory.Item {

    private int numSearchResults;

    //where searchString is the text the user has entered into the search
    private transient String searchString;

    public SiteSearch() {
        numSearchResults = 20;
        setStopWords(new SearchQueryBuilder.StopWords());
    }

    public Query<?> getQuery() {
        //initialize the query for search
        SearchQueryBuilder searchQuery = new SearchQueryBuilder();

        //set the types that you will search against
        Set<ObjectType> types = new HashSet<>();
        types.add(ObjectType.getInstance(Article.class));
        types.add(ObjectType.getInstance(Video.class));
        types.add(ObjectType.getInstance(Image.class));
        searchQuery.setTypes(types);

        //set the basic rules, followed by the rules set by editors
        searchQuery.onlyReturnPathedContent(true);
        searchQuery.addRules(getEditorialRules());

        //add the other search rules (boost represents powers of 10)
        searchQuery.addRule(new SearchQueryBuilder.BoostType(3, ObjectType.getInstance(Article.class)));

        return searchQuery.toQuery(null, searchString).sortRelevant(100000.0, "_any matchesAll ?", searchString);
    }

    public PaginatedResult<?> getSearchResults(long offset) {
        return getQuery().select(offset, numSearchResults);
    }

    @Override
    public String createPermalink(Site site) {
        return "/search";
    }
}
```

Hope that helps!

**Comment by DevDh** [comment]
Thanks very much for providing the detailed information on this.

For Form submission, if the com.psddev.dari.util.FormProcessor is deprecated, then what class should be used ? Please confirm.


Thanks,
Dev

**Comment by DevDh** [comment]
How to render the PaginationResult if it is of different ObjectType ?

**Comment by Ryan-Anderson** [comment]
@DevDh for the Form processing you can use an HttpServlet to handle the Form POST. 

http://docs.oracle.com/javaee/7/api/javax/servlet/ServletRequest.html#getParameter(java.lang.String)

As for your Second question about rendering PaginatedResult, using <cms:render> will delegate to the appropriate renderer for the given object.

**Comment by Ryan-Anderson** [comment]
Closing this issue for now, let us know if you have additional questions
