### ISSUE TITLE
How to handle the cms:form request

### ISSUE THREAD

**Issue by DevDh** [perfectsense/brightspot-cms#88]
Hi,

Using the Brightspot documentation, for the search functionality, I am using the <cms:form> with some input as shown below. I have the following questions:
1. On the form submit, the FormProcessor is not receiving the request. What is missed here ?
2. FormProcessor is deprecated in Brightspot 2.4 version, so what class to use to process the form requests ?

cms:form class="navbar-form navbar-right" id="searchForm" method="POST" processor="com.test.processor.SearchFormProcessor">
            <input type="text" class="form-control" placeholder="Search..." name="searchString">
</cms:form>"

Processor:
package com.test.processor;

import com.psddev.dari.util.FormProcessor;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

public class SearchFormProcessor implements FormProcessor {
    @Override
    public Object process(HttpServletRequest httpServletRequest, HttpServletResponse httpServletResponse) throws IOException {

        return "testing now";
    }
}

I would appreciate your response.

Thanks,
Dev

**Comment by DevDh** [comment]
Any input on this will be highly appreciated.

**Comment by kphenix** [comment]
Dev,

You can just use a normal form submit for this use case. The `cms:form` is not required for form submission. Just standard practice works great.

**Comment by DevDh** [comment]
Thanks for the input.
Is there any way to bind the user input data to the modal directly ?
For example user name to content.username.

**Comment by Ryan-Anderson** [comment]
There is not currently a way to bind form params directly to the model. In your HttpServlet you can use the POST params to set the appropriate fields.
