### ISSUE TITLE
Location field type map displays error message

### ISSUE THREAD

**Issue by nickdunn** [perfectsense/brightspot-cms#894]
The Location field type that displays a map is no longer working (Brightspot 2) as a result of MapQuest disabling access to their free tiles. http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/

Is there a quick fix to enter a MapQuest API key?

**Comment by nickdunn** [comment]
It looks like the Leaflet integration has now changed, and we must request MapQuest with an API key e.g. http://stackoverflow.com/a/38324489/4304424.

**Comment by hyoolim** [comment]
We're going to make this configurable, but you can work around the issue immediately by putting the following JS snippet into the Extra JavaScript field in CMS Debug Settings tab:

```
L.TileLayer.MapQuestOpenOSM = L.TileLayer.OpenStreetMap;
```

And yes, we'd also accept a PR if you'd like to create one.

**Comment by pnorman** [comment]
I just want to remind you that use of tile.openstreetmap.org is governed by the [tile usage policy](https://wiki.openstreetmap.org/wiki/Tile_usage_policy) and the priority for OSMF resources like tile.osm.org is serving mappers.

I have no idea what load would come from brightspot users, but this may be an issue and is something to consider.
