### ISSUE TITLE
[Documentation] Getting Started updates needed

### ISSUE THREAD

**Issue by gmazza** [perfectsense/brightspot-cms#981]
Hi, I'm going through the tutorial right now, found some problems/suggestions for two of the pages:

On page: http://documentation.brightspot.com/docs/3.2/getting-started/what-is-brightspot:

1.) "Brightspot was built using the Dari Framework, " -> good to switch hyperlink over Dari Framework from GitHub page to http://www.dariframework.org/ since a full website is now available for it.

2.) "Brightspot is open-source and freely available for use" --> good to add hyperlink over "freely available" to: https://github.com/perfectsense/brightspot-cms so people can immediately know where to get to the code.

On page: http://documentation.brightspot.com/docs/3.2/getting-started/hello-world:

3.) "Open the Brightspot application in a browser at http://localhost:8080/cms."  --> Because the simple version of the Getting Started page (http://documentation.brightspot.com/docs/3.2/getting-started/installation) has Brightspot running at port 9480, best to update that link to http://localhost:9480/cms.  (Those having the technical know-how to run the advanced Development Installation option on the Getting Started page will understand to switch the port number to 8080 anyway.)

4.) In the "Render Content" section, the tutorial is not telling us where to place the new page-container.jsp and article.jsp files.  Instruct the reader they should go under a new "render" folder under "webapp" in the archetype-generated project.  (That location worked for me at least, perhaps the team has a more preferred location.)

5.) In class ArticleListModule, add quotes to the JSP: @Renderer.Path("/article-list-module.jsp")  (Also may wish to switch to "/render/article-list-module.jsp" to make the location of this JSP consistent with the other two.)

6.) In the source code for article-list-module.jsp, add the necessary taglib declarations (as done in the two files above) to help those copying-and-pasting the code:

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="cms" uri="http://psddev.com/cms" %>

7.) In the QueryAPI section, the code necessary to show the article list on the web page (not the Dari code tool, that works fine) is incomplete and can't work as-is.  Suggested fixes:

a) Place interface RightRail _above_ ArticleListModule and have ArticleListModule's code sample implement RightRail.

b) In order for ArticleListModule to implement RightRail, three methods must be implemented:  getState, setState, as.  Place implementations of this in ArticleListModule so the class will compile.

c) Text says:  "You can use the &lt;cms:render> tag to render a list of content types, such as modules, and it will render each using their assigned Renderer.Path jsp." --> Be a little more direct for this 
tutorial, let us know what we need to add to page-container.jsp so we can see the ArticleListModule's data.

8.) For FeedServlet, change article.getBody() --> article.getBodyText().

9.) Below FeedServlet, to be consistent with other URLs, change http://www.yoursite.com/api-feed to http://localhost:9480/api-feed  (I wasn't able to get this to work yet, but that would probably be the correct URL for those going through this tutorial.)

**Comment by feichenlaub** [comment]
Thank you for your feedback. 

As you probably noticed, the "Getting Started" topic no longer exists because we replaced it with a set of getting-started tutorials, which are still a work in progress. However, some of the tutorials are available at http://docs.brightspot.com/cms/developers-guide/tutorials/index.html#. 

These tutorials are based on the Brightspot Tutorial project, which is easily installed. Please see the "Quick Installation" topic at http://docs.brightspot.com/cms/developers-guide/installation/quick.html.

We hope you find the tutorials comprehensive and easy to follow. Your feedback is always welcome.
